% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\kopfic{8}{CART}


\aufgabe{}{
<<child="ex_rnw/ex_research_group_cart.Rnw">>=
@
}

\newpage

\aufgabe{}{
<<child="ex_rnw/ex_tree_building_by_hand_surrogate_split_A.Rnw">>=
@
}
\aufgabe{}{
<<child="ex_rnw/ex_tree_building_by_hand_surrogate_split_B.Rnw">>=
@
}
% \aufgabe{}{
% <<child="ex_rnw/ex_tree_building_by_hand_surrogate_split_C.Rnw">>=
% @
% }
