% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
options(warn = -1)
@


\kopfic{8}{CART}

\loesung{}{
<<child="ex_rnw/sol_research_group_cart.Rnw">>=
@
}

\newpage

\loesung{}{
<<child="ex_rnw/sol_tree_building_by_hand_surrogate_split_A.Rnw">>=
@
}
\loesung{}{
<<child="ex_rnw/sol_tree_building_by_hand_surrogate_split_B.Rnw">>=
@
}
% \loesung{}{
% <<child="ex_rnw/sol_tree_building_by_hand_surrogate_split_C.Rnw">>=
% @
% }
