
Suppose you apply AdaBoost with a decision stump on the data set as in the following figure:

\begin{figure}[ht!]
	\centering
	\includegraphics[width=0.6\linewidth]{figure/boosting_simple}

\end{figure}

 
%
\begin{enumerate}
%	
	\item What would be a decision boundary for the first decision stump? 
%	
	\item How do the weights of the points change after the first iteration?
%	
	\item How many iterations are at least needed such that AdaBoost's training error is zero?
%	
\end{enumerate}
%