We will now visualize how well different learners classify the notoriously 
hard \texttt{mlbench::mlbench.spirals} data set.
Generate 1000 points from \texttt{spirals} (using the default standard 
deviation) and consider the classifiers already introduced in the lecture: 

\begin{itemize}
  \item logistic regression,
  \item LDA,
  \item QDA, and
  \item Naive Bayes.
\end{itemize}

Plot the learners' decision boundaries.
Can you spot differences in separation ability?