Implement you own version of QDA:\\

\texttt{trainQDA = function(target, data)}\\
\texttt{predictQDA = function(taget,data)}\\

The first function should return the fitted model (use an adequate structure for the model!). The second function should return a factor of classes for \texttt{type = 'class'} and a matrix of predicted probabilities for \texttt{type = 'prob'}. Your method does only need to work for numeric features. Check your implementation on the \texttt{iris} dataset and compare your results of both types with the \texttt{qda()} function from the package \texttt{MASS}.
