A is QDA, B and C are either LDA or Naive Bayes.
\begin{enumerate}
\item[1)] LDA can be seen as a special case of QDA if the covariance matrix is equal for all classes: $\Sigma_k = \Sigma \; \; \forall k$
\item[2)] Naive Bayes can be seen as a special case of QDA if the features are conditionally independent given class $k$:
\begin{align}
\pdfxyk = p((x_1, x_2, ..., x_p)|y = k)=\prodjp p(x_j|y = k),
\end{align}
which results in diagonal covariance matrices.
\item[3)] Naive Bayes and LDA have an intersection if the covariance matrix is equal for all classes: $\Sigma_k = \Sigma \; \; \forall k$ \textbf{and} features are conditionally independent given class $k$, leaving each class with the same diagonal covariance matrix $\Sigma$.
\end{enumerate}