% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfaml{6}{Imbalanced Learning}

\loesung{Performance Measures}{
	<<child="ex_rnw/sol_cost_sensitive_1.Rnw">>=
	@
}

\loesung{PR-curve}{
	<<child="ex_rnw/sol_cost_sensitive_2.Rnw">>=
	@
}


\loesung{MetaCost}{
	<<child="ex_rnw/sol_cost_sensitive_3.Rnw">>=
	@
}
