Draw the PR-curve for the following data set:


\begin{center}
	\begin{tabular}{c|c}
		
		\textbf{Truth} & \textbf{Score}  \\
		\hline
		Pos & 0.95 \\
		
		Pos & 0.86  \\
		
		Pos & 0.69  \\
		
		Neg &  0.65  \\
		
		Pos &  0.59 \\
		
		Neg  &  0.52 \\
		
		Pos &  0.51  \\
		
		Neg  &  0.39 \\
		
		Neg  &  0.28 \\
		
		Neg  &  0.18 \\
		
		Pos  & 0.15  \\
		
		Neg  &  0.06 \\
	\end{tabular}
\end{center}