% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{13}

\aufgabe{Entropy}{
	<<child="ex_rnw/ex_some_information.Rnw">>=
	@
}

\dlz

\aufgabe{Kullback-Leibler Divergence}{
	<<child="ex_rnw/ex_kld_binom_normal.Rnw">>=
	@
}
