[lecture]
title = 'Introduction to Machine Learning'
toc_title = 'Introduction to Machine Learning'
logo = 'local/logo.pdf'
paperwidth = '170.6666666667mm'
paperheight = '96mm'

[chapters]
'01-ml-basics' = 'ML Basics'
'02-supervised-regression' = 'Supervised Regression'
'03-supervised-classification' = 'Supervised Classification'
'04-evaluation' = 'Performance Evaluation'
'05-knn' = 'k-NN'
'06-cart' = 'Classification and Regression Trees (CART)'
'07-forests' = 'Random Forests'
'08-neural-networks' = 'Neural Networks'
'09-tuning' = 'Tuning'
'10-nested-resampling' = 'Nested Resampling'

[slides]
'01-ml-basics/01-whatisml.tex' = 'What is Machine Learning?'
'01-ml-basics/02-data.tex' = 'Data'
'01-ml-basics/03-task.tex' = 'Supervised Tasks'
'01-ml-basics/04-models-parameters.tex' = 'Models and Parameters'
'01-ml-basics/05-learner.tex' = 'Learner'
'01-ml-basics/06-riskminimization.tex' = 'Losses and Risk Minimization'
'01-ml-basics/07-optimization.tex' = 'Optimization'
'01-ml-basics/08-learnercomponents-hro.tex' = 'Components of Supervised Learning'
'01-ml-basics/09-nutshell.tex' = 'ML Basics'
'02-supervised-regression/01-linearmodel-l2.tex' = 'Linear Models with $L2$ Loss'
'02-supervised-regression/02-deepdive-ols.tex' = 'Deep Dive: Proof OLS Regression'
'02-supervised-regression/03-linearmodel-l1.tex' = 'Linear Models with $L1$ Loss'
'02-supervised-regression/04-polynomials.tex' = 'Polynomial Regression Models'
'02-supervised-regression/05-nutshell.tex' = 'Supervised Regression'
'03-supervised-classification/01-tasks.tex' = 'Classification Tasks'
'03-supervised-classification/02-basicdefs.tex' = 'Basic Definitions'
'03-supervised-classification/03-linear.tex' = 'Linear Classifiers'
'03-supervised-classification/04-logistic.tex' = 'Logistic Regression'
'03-supervised-classification/05-discranalysis.tex' = 'Discriminant Analysis'
'03-supervised-classification/06-naivebayes.tex' = 'Naive Bayes'
'03-supervised-classification/07-nutshell.tex' = 'Supervised Classification'
'04-evaluation/01-generr.tex' = 'Generalization Error'
'04-evaluation/02-measures-regression.tex' = 'Measures Regression'
'04-evaluation/03-train.tex' = 'Training Error'
'04-evaluation/04-test.tex' = 'Test Error'
'04-evaluation/05-overfitting-underfitting.tex' = 'Overfitting \& Underfitting'
'04-evaluation/06-resampling-1.tex' = 'Resampling 1'
'04-evaluation/07-resampling-2.tex' = 'Resampling 2'
'04-evaluation/08-measures-classification.tex' = 'Measures Classification'
'04-evaluation/09-rocbasics.tex' = 'ROC Basics'
'04-evaluation/10-roccurves.tex' = 'ROC Curves'
'04-evaluation/11-partialauc.tex' = 'Partial AUC'
'04-evaluation/12-mcauc.tex' = 'Multi-Class AUC'
'04-evaluation/13-prcurves.tex' = 'PR Curves'
'04-evaluation/14-auc-mwu.tex' = 'AUC \& MWU Test'
'04-evaluation/15-nutshell.tex' = 'Performance Evaluation'
'05-knn/01-knn.tex' = 'k-NN'
'06-cart/01-predictions.tex' = 'Predictions with CART'
'06-cart/02-treegrowing.tex' = 'Growing a Tree'
'06-cart/03-splitcriteria-regression.tex' = 'Splitting Criteria I'
'06-cart/04-splitcriteria-classification.tex' = 'Splitting Criteria II'
'06-cart/05-computationalaspects.tex' = 'Computational Aspects of Finding Splits'
'06-cart/06-stoppingpruning.tex' = 'Stopping criteria \& pruning'
'06-cart/07-discussion.tex' = 'Discussion'
'06-cart/08-nutshell.tex' = 'CART'
'07-forests/01-bagging.tex' = 'Bagging Ensembles'
'07-forests/02-basics.tex' = 'Basics'
'07-forests/03-oob.tex' = 'Out-of-Bag Error Estimate'
'07-forests/04-featureimportance.tex' = 'Feature Importance'
'07-forests/05-proximities.tex' = 'Proximities'
'07-forests/06-nutshell.tex' = 'Random Forests'
'07-forests/07-bagging-deepdive.tex' = 'Bagging: Deep Dive'
'08-neural-networks/01-intro-introduction.tex' = 'Introduction'
'08-neural-networks/02-mlps-single-neuron.tex' = 'Single Neuron'
'08-neural-networks/03-mlps-single-hidden-layer-networks.tex' = 'Single-Hidden-Layer NN'
'08-neural-networks/04-mlps-multiclass-classification.tex' = 'Single-Hidden-Layer Networks for Multi-Class Classification'
'08-neural-networks/05-mlps-multilayer-FNNs.tex' = 'MLP: Multi-Layer Feedforward Neural Networks'
'08-neural-networks/06-nutshell.tex' = 'Neural Networks'
'08-neural-networks/07-mlp-univ-approx-theorem.tex' = 'Universal Approximation Theorem'
'08-neural-networks/08-mlps-xor.tex' = 'XOR'
'08-neural-networks/09-mlps-matrix-notation.tex' = 'MLP: Matrix Notation'
'08-neural-networks/10-mlps-mlps-as-predictor.tex' = 'MLPs as Predictors'
'09-tuning/01-intro.tex' = 'Introduction'
'09-tuning/02-tuningproblem.tex' = 'Problem Definition'
'09-tuning/03-basicalgos.tex' = 'Basic Techniques'
'09-tuning/04-advanced.tex' = 'Advanced Techniques'
'09-tuning/05-pipelines.tex' = 'Pipelines and AutoML'
'09-tuning/06-nutshell.tex' = 'Tuning'
'09-tuning/07-practical.tex' = 'Practical Aspects'
'10-nested-resampling/01-nestedintro.tex' = 'Motivation'
'10-nested-resampling/02-trainvalidtest.tex' = 'Training - Validation - Testing'
'10-nested-resampling/03-nestedresampling.tex' = 'Nested Resampling'

[chapter_slides]
'01-ml-basics' = [
  '01-whatisml.tex',
  '02-data.tex',
  '03-task.tex',
  '04-models-parameters.tex',
  '05-learner.tex',
  '06-riskminimization.tex',
  '07-optimization.tex',
  '08-learnercomponents-hro.tex',
]
'02-supervised-regression' = [
  '01-linearmodel-l2.tex',
  '02-deepdive-ols.tex',
  '03-linearmodel-l1.tex',
  '04-polynomials.tex',
]
'03-supervised-classification' = [
  '01-tasks.tex',
  '02-basicdefs.tex',
  '03-linear.tex',
  '04-logistic.tex',
  '05-discranalysis.tex',
  '06-naivebayes.tex',
]
'04-evaluation' = [
  '01-generr.tex',
  '02-measures-regression.tex',
  '03-train.tex',
  '04-test.tex',
  '05-overfitting-underfitting.tex',
  '06-resampling-1.tex',
  '07-resampling-2.tex',
  '08-measures-classification.tex',
  '09-rocbasics.tex',
  '10-roccurves.tex',
  '11-partialauc.tex',
  '12-mcauc.tex',
  '13-prcurves.tex',
  '14-auc-mwu.tex',
]
'05-knn' = [
  '01-knn.tex',
]
'06-cart' = [
  '01-predictions.tex',
  '02-treegrowing.tex',
  '03-splitcriteria-regression.tex',
  '04-splitcriteria-classification.tex',
  '05-computationalaspects.tex',
  '06-stoppingpruning.tex',
  '07-discussion.tex',
]
'07-forests' = [
  '01-bagging.tex',
  '02-basics.tex',
  '03-oob.tex',
  '04-featureimportance.tex',
  '05-proximities.tex',
]
'08-neural-networks' = [
  '01-intro-introduction.tex',
  '02-mlps-single-neuron.tex',
  '03-mlps-single-hidden-layer-networks.tex',
  '04-mlps-multiclass-classification.tex',
  '05-mlps-multilayer-FNNs.tex',
  '09-mlps-matrix-notation.tex',
]
'09-tuning' = [
  '01-intro.tex',
  '02-tuningproblem.tex',
  '03-basicalgos.tex',
  '04-advanced.tex',
  '05-pipelines.tex',
]
'10-nested-resampling' = [
  '01-nestedintro.tex',
  '02-trainvalidtest.tex',
  '03-nestedresampling.tex',
]

[bundles.all]
title = 'Introduction to Machine Learning'
subtitle = 'All slides'
chapters = [
  '01-ml-basics',
  '02-supervised-regression',
  '03-supervised-classification',
  '04-evaluation',
  '05-knn',
  '06-cart',
  '07-forests',
  '08-neural-networks',
  '09-tuning',
  '10-nested-resampling',
]

[bundles.nutshell]
title = 'Introduction to Machine Learning: Nutshell'
subtitle = 'All slides'
slides = [
  '01-ml-basics/09-nutshell.tex',
  '02-supervised-regression/05-nutshell.tex',
  '03-supervised-classification/07-nutshell.tex',
  '07-forests/06-nutshell.tex',
  '08-neural-networks/06-nutshell.tex',
]
