% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
options(warn = -1)
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/ml-trees.tex}
\input{../../latex-math/ml-eval.tex}
\input{../../latex-math/ml-hpo.tex}
\input{../../latex-math/basic-ml.tex}


\kopfic{12}{Nested Resampling}

\loesung{}{
<<child="ex_rnw/sol_research_group_tuning-resampling.Rnw">>=
@
}
