% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{10}

\loesung{
<<child="ex_rnw/sol_cart_vs_knn.Rnw">>=
@
}

\dlz
\loesung{
<<child="ex_rnw/sol_automl.Rnw">>=
@
}

\dlz

\loesung{
<<child="ex_rnw/sol_kaggle.Rnw">>=
@
}



