Consider a case of binary classification, i.e., $y \in \{0,1\}$, where you only have a one-dimensional feature $\xv$.

\begin{enumerate}
\item Derive the decision regions for LDA, i.e., assuming that $\xv|y=k \distas \ \normal(\mu_k, \sigma^2)$ for $k \in \{0,1\}$
\item Derive the decision regions for QDA, i.e., assuming that $\xv|y=k \distas \ \normal(\mu_k, \sigma_k^2)$ for $k \in \{0,1\}$
\end{enumerate}

\textit{Hint}: In both parts, start with $\pdfxyk[0] = \pdfxyk[1]$ and solve for $\xv$.