After all that you have now learned about supervised machine learning, we want to use today's inverted classroom to think about some of the more practical aspects and challenges of training and deploying an ML model.
Nowadays, machine learning is applied in virtually all domains of society: business, government, health care, academia, NGOs, etc.
Imagine you are approached for your formidable skills as a data scientist and are asked to think of a \textbf{problem that (supervised) machine learning could help to solve}.

\begin{enumerate}\bfseries
  \item[1)] Develop a full ML use case.
  Make sure to think about all the necessary steps involved, from the first idea to deploying the model.
  Do not forget to consider the practical challenges of your project at each step.
  Use the mural whiteboard linked in this week's etherpad to write down your group's step-by-step process.
\end{enumerate}