% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{$k$-NN}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{$k$-NN with Manhattan Distance}{
<<child="ex_rnw/ex_knn_manh.Rnw">>=
@
}

\dlz
\loesung{
<<child="ex_rnw/sol_knn_manh.Rnw">>=
@
}

\aufgabe{$k$-NN from Scratch}{
<<child="ex_rnw/ex_knn_from_scratch.Rnw">>=
@
}

\dlz

\loesung{
See R file
}

\newpage

% ------------------------------------------------------------------------------
% PAST EXAMS
% ------------------------------------------------------------------------------

\dlz
\exexams
\lz

% ------------------------------------------------------------------------------
% INSPO
% ------------------------------------------------------------------------------

\dlz
\exinspo