Answer the following questions either with formal proof or a (meaningful!) simulation:\\
Which of the these feature-independent rules will result in a smaller expected error for the general 2-class-case:\\
\begin{itemize}
\item[(1)] Always predict the largest class from the training data. \\
\item[(2)] For a new observation, draw the class from the empirical probabilities of the classes in the training data. 
\end{itemize}
Or do both rules always have the same performance? 
