\begin{enumerate}

\item 

\begin{align*}
\sigma'(u) =& \frac{\partial\sigma(u)}{\partial u}\\
=&-\frac{1}{(1+\exp^{-u})^2}\cdot-\exp^{-u}\cdot-1\\
=&\frac{\exp^{-u}}{(1+\exp^{-u})^2}
\end{align*}

\item

\begin{align*}
(1 - \sigma(u)) \cdot \sigma(u) =& (1 - \frac{1}{1 + \exp^{-u}}) \cdot \frac{1}{1 + \exp^{-u}}\\
=&\frac{1}{1 + \exp^{-u}} - \frac{1}{(1 + \exp^{-u})^2}\\
=&\frac{1 + \exp^{-u} - 1}{(1 + \exp^{-u})^2}\\
=&\frac{\exp^{-u}}{(1+\exp^{-u})^2}
\end{align*}


\end{enumerate}