% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
options(warn = -1)
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{2}

% \loesung{
% <<child="ex_rnw/sol_knn_manh.Rnw">>=
% @
% }
% 
% \dlz
% 
% \loesung{
% <<child="ex_rnw/sol_lrn.Rnw">>=
% @
% }
% 
% \loesung{
% 
% See 
% \href{https://github.com/compstat-lmu/lecture_i2ml/blob/master/exercises/supervised-regression/ex_rnw/sol_knn_lm.R}{R code}
% }
