## $K$-means Example

```{r, fig.width = 7, fig.height = 5, fig.align="center", echo=FALSE, message=FALSE, results="asis"}
set.seed(1234)
pts = iris[, 3:4]

iters = 3
K = 3
km = vector("list", iters)
centers = vector("list", iters + 1)

centers[[1]] = pts[sample.int(nrow(pts), K), , drop = FALSE] #matrix(c(1,0.5,2,1,7,2), ncol = 2, byrow = TRUE)

par(mar = c(4,4,3,0))
plot(pts, pch = 19, col = "gray70")
points(centers[[1]][, 1], centers[[1]][, 2], pch = 4, cex = 1.5, lwd = 2, col = "darkred")
title(main = "Iteration 0", line = 2)
title(main = "Choose K arbitrary observations to be the initial cluster centers", line = 1, cex.main = 0.8)
  
for (i in 1:iters) {
  cat("  \n##", "$K$-means Example  \n  \\addtocounter{framenumber}{-1}  \n")
  km[[i]] = kmeans(pts, centers = centers[[i]], nstart = 1, algorithm = "Lloyd", iter.max = 1)
  
  col = km[[i]]$cluster
  plot(pts, pch = 19, col = col)
  title(main = paste("Iteration", i), line = 2)
  title(main = "Assign observations to nearest cluster center", line = 1, cex.main = 0.8)
  points(centers[[i]][, 1], centers[[i]][, 2], pch = 4, cex = 1.5, lwd = 2, col = "darkred")
  
  cat("  \n")
  cat("  \n##", "$K$-means Example  \n  \\addtocounter{framenumber}{-1}  \n")
  
  centers[[i + 1]] = km[[i]]$centers
  plot(pts, pch = 19, col = col)
  points(centers[[i + 1]][, 1], centers[[i + 1]][, 2], pch = 4, cex = 1.5, lwd = 2, col = "darkred")
  title(main = paste("Iteration", i), line = 2)
  title(main = "Compute new cluster center", line = 1, cex.main = 0.8)
  cat("  \n")
}
```

<!-- Select 3 random points and assume them to be cluster centers for the clusters to be created. -->

## $K$-means in R

The $K$-means algorithm is part of the base distribution in R, given by
the `kmeans` function (using `algorithm = "Lloyd"`):

```{r, echo = TRUE, size = "tiny"}
km = kmeans(iris[,3:4], centers = 3, nstart = 100, iter.max = 100, algorithm = "Lloyd")
str(km)
```

## $K$-means in R

The final cluster assignments can be visualized by

```{r, fig.height = 5, out.width = "\\textheight", fig.align="center", echo = 2}
par(mar = c(4,4,1,1))
plot(iris[,3:4], pch = 19, col = km$cluster)
```
