## Example: Hierarchical Clustering

In R:

```{r}
simple.data = data.frame(
  x = c(0.2,0.3,0.4,0.85,0.85), 
  y = c(0.4,0.65,0.6,0.7,0.9)
)
# compute distance matrix
euclid = dist(simple.data, method = "euclidean")
# do clustering with complete linkage
agglo = hclust(euclid, method = "complete")
agglo
```

## Example: Dendrogram in R

```{r, out.width="\\textwidth", fig.width=8, fig.height=4, echo=2}
par(mar = c(2,4,1,1))
plot(agglo)
```

## Example: Dendrogram in R

```{r, out.width="\\textwidth", fig.width=8, fig.height=4, echo=2}
par(mar = c(2,4,1,1))
plot(agglo, hang = -1) # labels at each node "hang down" until height 0
```

## Example: Dendrogram in R

A horizontal line partitions the observations into clusters and shows a specific state of the hierarchical clustering procedure.

```{r, out.width="0.7\\textwidth", fig.width=8, fig.height=4, echo=c(2:6)}
par(mar = c(2,4,1,1))
plot(agglo, hang = -1) 
rect.hclust(agglo, k = 2, border = 2)
rect.hclust(agglo, k = 3, border = 3)
legend("topright", legend = c("2 clusters", "3 clusters"), 
  lty = 1, col = 2:3)
```
