% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\section*{I2ML -- Test exam -- WS2022/23}

\aufgabe{Polynomial regression}{
	<<child="ex_rnw/ex_poly.Rnw">>=
	@
}

\aufgabe{ROC}{
	<<child="ex_rnw/ex_roc_island.Rnw">>=
	@
}

\dlz

\aufgabe{$k$-NN}{
	<<child="ex_rnw/ex_knn_gower.Rnw">>=
	@
}


\dlz

\aufgabe{LDA}{
	<<child="ex_rnw/ex_lda_qda.Rnw">>=
	@
}