% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\section*{I2ML -- Test exam -- WS2022/23}

\loesung{Polynomial regression}{
<<child="ex_rnw/sol_poly.Rnw">>=
@
}
\dlz

\loesung{ROC}{
<<child="ex_rnw/sol_roc_island.Rnw">>=
@
}

\dlz

\loesung{$k$-NN}{
<<child="ex_rnw/sol_knn_gower.Rnw">>=
@
}

\dlz
\loesung{LDA}{
<<child="ex_rnw/sol_lda_qda.Rnw">>=
@
}

