---
title: "Content"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

[Intro Video - Hello, Everyone!](https://www.youtube.com/watch?v=R9f4TFRntv0)

## Day 1

<a href="https://compstat-lmu.shinyapps.io/01_tutorial/" target="_blank">**Tutorials**</a> **|** <a href="https://github.com/compstat-lmu/lecture_i2ml/blob/master/exercises-pdf/exercise-day1.pdf" target="_blank">**Exercise Sheet**</a> **|** <a href="https://docs.google.com/document/d/1MIvhEw-mLu_iZ01dkaGJcqLlZB2I0LL9nSceoloCqww/edit?usp=sharing" target="_blank">**Questions/Comments**</a>

- Slot 1: Introduction to machine learning (ML) [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-intro.pdf)|[video](https://youtu.be/2BWKlAOayQI)]
- Slot 2: What are ML tasks? [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-tasks.pdf)|[video](https://youtu.be/ST-VsUdbufo)]
- Slot 3: k-nearest neighbors [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-knn.pdf)|[video](https://youtu.be/GOsXMlzsSiQ)]
- Slot 4: Basic learning theory: Loss functions [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-loss.pdf)|[video](https://youtu.be/PIj0HR4lUOg)]
- Slot 5: Linear regression as a ML model [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-limo.pdf)|[video](https://youtu.be/saf0rLmoEjE)]

## Day 2

<a href="https://compstat-lmu.shinyapps.io/02_tutorial/" target="_blank">**Tutorials**</a>

- Slot 1: Theory of classification [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-classification.pdf)|[video](https://youtu.be/ZuGbjJAETdA)]
- Slot 2: Logistic regression as a ML model [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-logistic.pdf)|[video](https://youtu.be/VUa49fo82q4)]
- Slot 3: Classification approaches [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-classification-approaches.pdf)|[video](https://youtu.be/yZ5SUWm2zbg)]
- Slot 4: Two cultures of modeling [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-cultures.pdf)|[video](https://youtu.be/7YTswPpzxO4)]

## Day 3

<a href="https://compstat-lmu.shinyapps.io/03_tutorial/" target="_blank">**Tutorials**</a>

- Slot 1: Introduction to performance evaluation [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-intro-performance.pdf)|[video](https://youtu.be/e4twP-lMPVI)]
- Slot 2: Simple performance metrics [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-measures.pdf)|[video](https://youtu.be/YPkNPGrdGoY)]
- Slot 3: Overfitting [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-overfitting.pdf)|[video](https://youtu.be/-S5h9ayrXh4)]
- Slot 4:
    * ROC analysis part 1 [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-roc-1.pdf)|[video](https://youtu.be/lPHTqGWRciQ)]
    * ROC analysis part 2 [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-roc-2.pdf)|[video](https://youtu.be/1bitCgn_D6o)]
    * ROC Demo App [[Link]](https://fabian-s.shinyapps.io/roc_shiny/)
- Slot 5: Resampling [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-resampling.pdf)|[video](https://youtu.be/eeCtAVkAvSI)]

## Day 4

<a href="https://compstat-lmu.shinyapps.io/04_tutorial/" target="_blank">**Tutorials**</a>

- Slot 1:
    * CART Part 1 [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-cart1.pdf)|[video](https://youtu.be/ZdJ7W-gEkJg)]
    * CART Part 2 [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-cart2.pdf)|[video](https://youtu.be/k-OFfj2Y0OY)]
- Slot 2:
    * Random Forest Part 1 [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-forests1.pdf)|[video](https://youtu.be/P34_SbEwEh8)]
    * Random Forest Part 2 [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-forests2.pdf)|[video](https://youtu.be/Zpj6znkzO2M)]

## Day 5

<a href="https://compstat-lmu.shinyapps.io/05_tutorial/" target="_blank">**Tutorials**</a>

- Slot 1: Hyperparameter Tuning [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-tuning.pdf)|[video](https://youtu.be/5F5wBZ-WjI8)]
- Slot 2: Nested Resampling [[pdf](https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-nested-resampling.pdf)|[video](https://youtu.be/aV__yAFzNtc)]


