---
title: "LMU Course"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## General information

This course mainly "lives" on the web, but is complemented by a week-long inverted-classroom week long block course at the LMU, 
which statistics and data science students can enroll in.
We also welcome students from computer science or any other institute or faculty, as long we have enough space and resources available. 

## Flipped classroom block course

The active part - solving exercises, discussing material - will happen during the block course, while the passive part - watching course videos, reading material - will happen on your own time and at a place of your choice. 

**It is extremely important that you watch and try to understand all of the course material and work on the tutorials before we meet for class!** 
The exercises, code demos and activities that we will work on together during the block course all depend on the knowledge you gain by working on the course materials *in advance*. This is not a passive, lecture-type course -- you need to be active yourself and prepare each day in a self-directed fashion like the responsible adult that you are.

## Important dates and info for winter term 2018/19

- The course is targeted at 4th semester Bachelor students (stats)
- **LMU block course**: 11.3. - 15.3.2019
- **Location**: Room 211, Amalienstr. 73A VU104 at Prof.-Huber-Platz
- **Moodle key:** IntroML
- **Moodle link:** https://moodle.lmu.de/course/view.php?id=4392
- 3 ECTS
- This lecture can be recognised as 
    - WP2, WP6.0.3 + WP6.0.4 or WP8 (Bachelor Statistics)
    - Biostatistik-Master: Ausgew채hlte Gebiete der Biostatistik B oder C
    - WiSo-Master: Ausgew채hlte Gebiete der Sozialstatistik B oder Ausgew채hlte Gebiete der Wirtschaftsstatistik B
    - Methoden-Master: Ausgew채hlte Gebiete der theoretischen Statistik B oder D
- Course material, including videos, will be in English, course will be held in English
- **Please bring your laptop for the practical work!**

## Moodle

- The LMU moodle page provide a short overview of LMU specific course information
- Everything else is on Github
- You HAVE to enroll in moodle and you will HAVE to register for the exam there
- We will use moodle to communicate with you 

## Daily schedule for LMU course

- 9:30 (s.t.) - 11:00: Discussion of exercises from day before 
- 11:00 - 12:00 Code demos in R
- **12:00 - 13:00 Lunch break**
- 13:00 - 15:00 Solving exercises in groups/alone (supervised) 
- 15:00 - 17:00 Unsupervised self study / Work on practical exercises in groups (See, we also cover unsupervised learning ... Sorry.)

## Other lectures of interest 

- In summer, Bernd teaches *Predictive Modelling / FCIM*. You should have taken this I2ML before.
- In winter, Bernd teaches *Deep Learning*. You should have taken *Predictive Modelling* before.
- Why not work on an ML project during statistical consulting, the data science practical or the data science innovation lab?
- Why not approach Bernd's or Fabian's group for an ML related student research project? 
  You can get ECTS for that, too.
- We will try to provide more ML related seminars.



