---
title: "References"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{"References"}
---

## Major references

The course material covers all exam relevant topics. For a deeper study of the courses and additional machine learning topics, we recommend the following literature:

* G. James, D. Witten, T. Hastie, R. Tibshirani. An Introduction to Statistical Learning. MIT Press, 2010. [link](http://www-bcf.usc.edu/~gareth/ISL/)

## More advanced books

The following books are great, but quite detailed and involved, and more geared towards a larger lecture in a Master's degree.

* T. Hastie, R. Tibshirani, J. Friedman. The Elements of Statistical Learning. Springer, 2009. [link](https://web.stanford.edu/~hastie/ElemStatLearn/)
* K. Murphy. Machine Learning: a Probabilistic Perspective [link](https://www.cs.ubc.ca/~murphyk/MLbook/)
* E. Alpaydin. Introduction to Machine Learning. MIT Press, 2010. [link](http://www.cmpe.boun.edu.tr/~ethem/i2ml2e/)
* C. M. Bishop. Pattern Recognition and Machine Learning. Springer, 2006. [link](http://research.microsoft.com/en-us/um/people/cmbishop/prml/)

## R

We use the *mlr3* package for machine learning in R.

* Central project page and learning ressources: https://mlr3.mlr-org.com/
* Github page: https://github.com/mlr-org/mlr3

The first link contains a section "Ressources" which lists all available background information to enable you to learn the toolkits.
Please study those. Most important (for you as new users) are the book, the gallery, the cheatsheets. 
Use the usual R package manuals for formal library documentation.
It might be good to watch the 2 short intro video from the UseR 2019 to get a quick overview in less than an hour.

