---
title: "Contributors"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

-   [Bernd Bischl](https://www.compstat.statistik.uni-muenchen.de/people/bischl/)
    - Bernd wrote the initial version of most the course material, and teaches various master courses in ML and DL at the LMU for stats and data science.
-   [Fabian Scheipl](https://www.biostat.statistik.uni-muenchen.de/personen/mitarbeiter/scheipl/index.html)
    - Fabian contributed (marginally) to the slides and quizzes and was asked to participate primarily because of his good looks and his funny Bavarian-English. Bernd says: Fabian is a great teacher, and was the first to provide video-based course content for his amazing course on advanced R programming at the LMU. As he is also an expert in predictive modelling. I am extremly happy that we joined the team in fall 2018.
-   [Christoph Molnar](https://www.compstat.statistik.uni-muenchen.de/people/molnar)
    - Christoph is a PhD at Bernd's group and organized the first round of the inverted classroom in spring 2018, including the first round of videos.
-   [Daniel Schalk](https://www.compstat.statistik.uni-muenchen.de/people/schalk)
    - Daniel is a PhD at Bernd's group and organized the second round of the inverted classroom in spring 2019; he also provided the digital platform for videos, quizzes and exercises. 
