---
title: "Uni Bielefeld Course"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{"Uni Bielefeld Course"}
---


## General information

This course is partly an online course, partly a week long block course at Bielefeld University.


## Flipped classroom block course

The active part - solving exercises, discussing material - will happen during the block course, while the passive part - watching course videos, reading material - will happen on your own time and at a place of your choice. 

**It is extremely important that you watch the videos and try to understand the course material before we meet for class!** 
The exercises, code demos and activities that we will work on together during the block course all depend on the knowledge you gain by working on the course materials *in advance*. This is not a passive, lecture-type course -- you need to be active yourself and prepare each day in a self-directed fashion like the responsible adult that you are.



### In-Person class

The in-person classes will be **Monday 16.03 to Friday 20.03.2020**.

We will try to more or less stick to the following schedule:

- 09:30 - 11:00 Discussion of exercises from day before + Questions about course content
- 11:00 - 12:00 Code demos in R
- **12:00 - 13:00 Lunch break**
- 13:00 - 15:00 Solving exercises in groups/alone (supervised) 
- 15:00 - 17:00 Unsupervised self study / Work on practical exercises in groups 


## Moodle

All course specific information is available on [Moodle](https://lernraumplus.uni-bielefeld.de/course/view.php?id=4330) (LernraumPLUS).
You HAVE to enroll in moodle and you will HAVE to register for the exam there.
We will use Moodle to communicate with you. 









