<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{2}

\aufgabe{
<<child="exercises/ex_logreg_decision_boundaries.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="exercises/ex_mlr_decision_boundaries.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="exercises/ex_softmax.Rnw">>=
@
}

\aufgabe{
<<child="exercises/ex_naive_bayes.Rnw">>=
@
}

\dlz
