<<setup-child, include=FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\kopf{2}


\loesung{
<<child="exercises/sol_logreg_decision_boundaries.Rnw">>=
@
}

\loesung{
See R code \href{https://github.com/compstat-lmu/lecture_i2ml/blob/master/exercises/day2/exercises/sol_mlr_decision_boundaries.R}{\textbf{sol\_mlr\_decision\_boundaries.R}}
}

\dlz


\loesung{
<<child="exercises/sol_softmax.Rnw">>=
@
}

\newpage

\loesung{
<<child="exercises/sol_naive_bayes.Rnw">>=
@
}

\dlz
