How in mlr3 a learner can be constructed and what it represents can be found 
at \url{https://mlr3book.mlr-org.com/learners.html}.
\begin{enumerate}
\item[a)] How does a learner in mlr3 compare to what you've learned in the videos?
\item[b)] Pick an mlr3 learner of your choice. What are the different settings for this learner? \\ 
(Hint: Use \texttt{mlr\_learners\$keys()} to see all available learners)
\end{enumerate}