\begin{enumerate}
\item Take a look at the \texttt{spam.task} from \texttt{mlr}. Shortly describe what kind of classification problem this is.
\item Use a random forest to fit the model and plot the oob-error against the number of trees used.
\item Crossvalidate the random forest and compare the test error to the oob-estimator. Also compare both values to the crossvalidation error of CART.
\item Your boss wants to have only have a small number of variables in the model and wants to know which variables have the biggest influence on the prediction quality. Explain your approach in words as well as code.
\end{enumerate}