The fractions of the classes $k=1,\ldots, g$ in node $\mathcal{N}$ of a decision tree are $p(1|\mathcal{N}),\ldots,p(g|\mathcal{N})$.
Assume we replace the classification rule in node $\mathcal{N}$

\begin{eqnarray*}
\hat{k}|\mathcal{N}=\arg\max_k p(k|\mathcal{N})
\end{eqnarray*}
with a randomizing rule, in which we draw the classes in one node from their estimated probabilities.

Derive an estimator for the misclassification rate in node $\mathcal{N}$.
What do you (hopefully) recognize?


