What is the relationship between the cross entropy loss $L(y, f(x)) = - y \ln(\pi(x) - (1-y)\ln((1-\pi(x)))$ for $y \in\{0, 1\}$ and the bernoulli distribution $y \sim Bin(1, \pi(x))$?

\begin{enumerate}
  \item Derive the negative log likelihood of the bernoulli distribution.
  \item Derive the derivative of the negative likelihood as the cross entropy loss function for binary classification.
\end{enumerate}

