Take a look at the \texttt{eeg-eye-state} data from \url{http://www.openml.org/d/1471}.


Try to find the best model you can to fit the target.

Make use of everything you've learned in this lecture:

\begin{itemize}
\item Test different machine learning models. 
\item Use hyperparameter tuning.
\item Use variable selection techniques.
\end{itemize}


If you found a good model, upload your run to OpenML and compare it to the other runs.





