Based on the code demo from today, make your own submission to kaggle for the Titanic survival challenge. 
\begin{itemize}
  \item Try out different classification models you learned about the course (or maybe even something new?)
  \item Improve the prediction creating new features (feature engineering)
  \item Tune your parameters using random search (see: \url{https://mlr-org.github.io/mlr-tutorial/devel/html/tune/index.html})
  \item How big are the differences between your own performance estimate and on the public leaderboard?
\end{itemize}