Based on the code demo from today, make your own submission to kaggle for the Titanic survival challenge. 
\begin{itemize}
  \item[a)] Try out different classification models you learned during the course (or maybe even something new?)
  \item[b)] Improve the prediction by creating new features (feature engineering)
  \item[c)] Tune your parameters using random search (see: \url{https://mlr.mlr-org.com/articles/tutorial/tune.html})
  \item[d)] How big are the differences between your own performance estimate and the estimate of the public leaderboard?
\end{itemize}