We want to predict the age of an abalone using its Longest shell measurement and its weight.

See: http://archive.ics.uci.edu/ml/datasets/Abalone for more details.

Using mlr-package we want to:

a) plot "LongestShell", "WholeWeight" and color points with "Rings"

b) Fit lm

c) Fit knn

d) plot surface of lm and of knn

e) compare which classifier is better suited for data structure


ODER:


spiral dataset in \text{lm\_knn\_1b}?