Use three different methods (training, training-test, CV) to estimate the performance of a knn model  on a dataset of your choice from the \texttt{mlbench} package. For (a) and (b) split data into training and testing.

(a) Estimate the performance using the training sample. \\
(b) Estimate the performance using the test sample. \\
(c) Estimate the performance using cross validation. Hint: Use mlr functions makeResampleDesc and resample \\
(d) Compare the performance measures. Which one should one use?\\
