Shortly answer the following questions:

\begin{itemize}
\item Which of the following methods yield an unbiased generalization error estimate? Performance estimation ...
\begin{itemize}
  \item  on training data
  \item  on test data
  \item  on training and test data combined
  \item  using cross validation
  \item  using subsampling
\end{itemize}
\item Which problem do resampling strategies solve?
\item Which problem does nested resampling solve?
\end{itemize}
