(a) multiclass classification (plate digits) (supervised learning)

(b) binary classification (supervised)

(c) outlier detection ((un)supervised)

(d) frequency pattern mining (unsupervised)

(e) classification (supervised) / clustering (unsupervised)

(f) classification (supervised)

(g) clustering / assocation rules (unsupervised)

(h) not a machine learning task

(i) not a machine learning task
