% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfaml{7}{Multi-target Prediction}

\loesung{Multivariate Regression}{
	<<child="ex_rnw/sol_multitarget_1.Rnw">>=
	@
}

\loesung{Conditional Random Fields vs. Structured SVMs}{
	<<child="ex_rnw/sol_multitarget_2.Rnw">>=
	@
}

