# Intro: What is machine learning

## Machine learning is changing the world
- Search engines learn what you want
- Recommender systems learn your taste in books, music, movies,...
- Algorithms do automatic stock trading
- Elections are won by understanding voters
- Google Translate learns how to translate text
- Siri learns to understand speech
- DeepMind beats humans at Go
- Cars drive themselves
- Medicines are developed faster
- Smartwatches monitor your health
- Data-driven discoveries are made in Physics, Biology, Genetics, Astronomy, Chemistry, Neurology,...

## Famous quotes

## Motivation

## Supervised Learning

## Regression task

### Example Boston housing

## Binary classification task

### Example dataset: Spam dataset

## Multiclass classification task

### Example: iris

## Multilabel Classification task (eventuell weglassen)

## Cost sensitive classification task (eventuell weglassen)

### Loan example

## Forecasting task

## Survival task

## Clustering task

## Dimensionality reduction task

## Outlier Detection task

## Association rules task

## Semi-supervised learning
- classification
- clustering

## active learning

## Reinforcement learning

## Topics of the lecture
- kNN, geometry based learner
- loss
- linear model
- Decision Trees and Forests
- Machine Learning in R
-


## The two cultures of statistical learning

## Terminology





# Geometric or distance based approach

# kNN

# Loss minimization

## Dummy model

## Linear model





# Notes:
- Übungsaufgabe und Klausuraufgabe: Identifizieren was für ein Task vorliegt gegeben Textbeschreibung
- Quiz: Guess the learning task type (via smartphone)


h
