<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\kopf{1}

\aufgabe{
<<child="../single-exercises/lin_reg_a_1.Rnw">>=
@
}

\dlz	

\aufgabe{
<<child="../single-exercises/types_a_1.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="../single-exercises/knn_manh_a_1.Rnw">>=
@
}

\dlz	

\aufgabe{
<<child="../single-exercises/med_manh_a_1.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="../single-exercises/lm_knn_a_1.Rnw">>=
@
}



