<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\kopf{1}


\aufgabe{
<<child="exercises/types_a_1.Rnw">>=
@
}

\dlz
\aufgabe{
<<child="exercises/lin_reg_a_1.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="exercises/med_manh_a_1.Rnw">>=
@
}

\pagebreak[2]

\dlz
\aufgabe{
<<child="exercises/knn_manh_a_1.Rnw">>=
@
}

\dlz


\aufgabe{
<<child="exercises/lm_knn_a_1.Rnw">>=
@
}
