<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\kopf{1}

\loesung{
<<child="../single-exercises/lin_reg_l_1.Rnw">>=
@
}

\loesung{
<<child="../single-exercises/types_l_1.Rnw">>=
@
}

\loesung{
<<child="../single-exercises/knn_manh_l_1.Rnw">>=
@
}

\loesung{
<<child="../single-exercises/med_manh_l_1.Rnw">>=
@
}

\loesung{
See R code \textbf{lm\_knn\_l\_1a.R}
}


\dlz
