\begin{itemize}
\item The training performance is too optimistic  (kappa of 1), because the kappa is lower on new data.
\item The test performance is unbiased, but it depends on the split, as can be seen in the CV folds: 
Each CV fold represents a training test split and the kappa measure varies between folds.
\item The CV estimate averages over the different splits and gives an unbiased, more robust estimate.
\item The CV estimate is preferable over the other two, but more computationally expensive.
\end{itemize}
