Assume we use quadratic loss and measure instability of the ensemble with
$$\ambifM = \tfrac{1}{M}\sum^M_{m} \left(\blm- \fM \right)^2.$$
Show that the variance of the bagging prediction depends on the correlation between trees.

%Hint: compute $\text{Var}(\frac{1}{B}\sum_{b=1}^B f_b)$ when $\text{Var}(f_b)=\sigma^2$ and $\text{Corr}(f_i, f_j) = \rho$, where $f_b$ is a single tree of the ensemble.
