% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{Advanced Risk Min}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{Risk Minimization and Gradient Descent (Part 1)}{
<<child="ex_rnw/ex_linear_model_optim.Rnw">>=
@
}

\dlz

\aufgabe{Risk Minimization and Gradient Descent (Part 2)}{
<<child="ex_rnw/ex_lm_optim_part_2.Rnw">>=
@
}

\dlz

\aufgabe{Connection between MLE and ERM}{
<<child="ex_rnw/ex_glm_optim.Rnw">>=
@
}

\dlz

\aufgabe{Risk Minimizers for Generalized L2-Loss}{
<<child="ex_rnw/ex_advriskmin_1_22.Rnw">>=
@
}

% % ------------------------------------------------------------------------------
% % PAST EXAMS
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exexams
% \lz
% 
% % ------------------------------------------------------------------------------
% % INSPO
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exinspo