% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@
  
\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
 
\begin{center}
{\large
\textbf{Advanced Machine Learning}\\
\textbf{-- Mock Exam (2nd Part) --} \\
\textbf{-- Solution --}}
\end{center}
\aufgabe{Questions}{
	<<child="ex_rnw/sol_questions.Rnw">>=
	@
} 
\lz
\aufgabe{Fairness}{
	<<child="ex_rnw/sol_fairness.Rnw">>=
	@
} 
\lz
\aufgabe{Imbalanced Learning}{
	<<child="ex_rnw/sol_imbalanced_learning.Rnw">>=
	@
}
\lz
\aufgabe{Multi-target Prediction}{
	<<child="ex_rnw/sol_mtp.Rnw">>=
	@
}
\lz
\aufgabe{Online Learning}{
	<<child="ex_rnw/sol_online_learning.Rnw">>=
	@
}



