% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfsl{9}{Regularization}



\aufgabe{L0 Regularization}{
	<<child="ex_rnw/ex_regularization_1_22.Rnw">>=
	@
}
\dlz


\aufgabe{Regularization}{
	<<child="ex_rnw/ex_capacity_regularization.Rnw">>=
	@
}
