% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfsl{4}

\aufgabe{Hypothesis Space, Capacity, Regularization}{
	<<child="ex_rnw/ex_capacity_regularization.Rnw">>=
	@
}
\dlz

\aufgabe{Lasso, Subdifferentials}{
	<<child="ex_rnw/ex_lasso_subdifferential.Rnw">>=
	@
}