% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfsl{9}{Regularization}


\loesung{L0 Regularization}{
<<child="ex_rnw/sol_regularization_1_22.Rnw">>=
@
}
\dlz

\loesung{Regularization}{
	<<child="ex_rnw/sol_capacity_regularization.Rnw">>=
	@
}
