% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfsl{4}

\loesung{Hypothesis Space, Capacity, Regularization}{
<<child="ex_rnw/sol_capacity_regularization.Rnw">>=
@
}
\newpage

\loesung{Lasso, Subdifferentials}{
<<child="ex_rnw/sol_lasso_subdifferential.Rnw">>=
@
}