% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopfaml{5}{Fairness}

\loesung{Equivalent Representation of Separation and Sufficiency}{
	<<child="ex_rnw/sol_fairness_1.Rnw">>=
	@
}

\loesung{Fairness Measure}{
	<<child="ex_rnw/sol_fairness_2.Rnw">>=
	@
}


\loesung{Calibration}{
	<<child="ex_rnw/sol_fairness_3.Rnw">>=
	@
}
