In logistic regression, we estimate the probability $\pix = \post$.
To decide if $\hat{y}$ is $0$ or $1$, we follow:

$$
\hat{y} = 1 \ \ \Leftrightarrow \ \ \pixh \geq c
$$


\begin{itemize}
\item[a)] What happens if you are choosing $c = 0.5$? More precisely, from which value of $\thetab^T \xv$ do you predict $\hat{y} = 1$ rather than $\hat{y} = 0$?
\item[b)] Explain (using words) why $c = 0.5$ is a sensible threshold.
\end{itemize}
