% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{Advanced Risk Min}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{Multiclass and Softmax Regression}{
<<child="ex_rnw/ex_softmax_mnist.Rnw">>=
@
}

\dlz

\aufgabe{Logistic Regression, Softmax, Cross-Entropy}{
<<child="ex_rnw/ex_lt_softmax_theory_wo_mlr.Rnw">>=
@
}

% 
% % ------------------------------------------------------------------------------
% % PAST EXAMS
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exexams
% \lz
% 
% % \aufgabeexam{WS2020/21}{first}{1}{
% % foo
% % }
% % 
% % \dlz
% % \loesung{
% % bar
% % }
% 
% % ------------------------------------------------------------------------------
% % INSPO
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exinspo