% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopfsl{2}

\aufgabe{Multiclass and Softmax Regression}{
	<<child="ex_rnw/ex_softmax_mnist.Rnw">>=
	@
}
\dlz

\aufgabe{Logistic Regression, Softmax, Cross-Entropy}{
	<<child="ex_rnw/ex_lt_softmax_theory_wo_mlr.Rnw">>=
	@
}