\exercise

```{r, echo=FALSE, cache=FALSE}
if (! exists("solution")) {
  solution = FALSE
}
```

Apply the $K$-means algorithm to the `ruspini` data.

  a) Use `nstart = 10` and repeat the $K$-means algorithm assuming $k = 2, \hdots, 8$ clusters.
     Store the `tot.withinss` for each value of $k$ in a vector called `wss`.
  b) Now choose the *best* value for the number of clusters $k$ and visualize the result.\
  **Hint:** You can plot the result from a) using `plot(2:8, wss, type = "b")`. 


```{r, results="asis", echo=FALSE, eval=solution}
cat("__Solution__:")
```

```{r, echo = solution, eval = solution}
# a)
set.seed(1)
K = 8

wss = sapply(2:K, function(k) {
  kmeans(ruspini, centers = k, nstart = 10, algorithm = "Lloyd")$tot.withinss
})
wss

# b)
plot(2:K, wss, type = "b", xlab = "K (# of clusters)", ylab = "within-cluster variation")

# Ellbow is for K = 4 clusters
km = kmeans(ruspini, centers = 4, nstart = 10, algorithm = "Lloyd")
plot(ruspini, col = km$cluster, pch = 19)
```

