% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopf{Support Vector Machine}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{SVM -- Support Vectors and Separating Hyperplane}{
	<<child="ex_rnw/ex_linsvm_hyperplane.Rnw">>=
	@
}

\dlz

\aufgabe{SVM -- Optimization}{
	<<child="ex_rnw/ex_linsvm_subgradient.Rnw">>=
	@
}

\dlz

\aufgabe{SVM -- Kernel Trick}{
	<<child="ex_rnw/ex_kernel_trick.Rnw">>=
	@
}

% 
% % ------------------------------------------------------------------------------
% % PAST EXAMS
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exexams
% \lz
% 
% \aufgabeexam{WS2020/21}{first}{1}{
% foo
% }
% 
% \dlz
% \loesung{
% bar
% }
% 
% % ------------------------------------------------------------------------------
% % INSPO
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exinspo