% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopfsl{10}{Nonlinear Support Vector Machines}

\aufgabe{Kernelized Muliclass SVM}{
	<<child="ex_rnw/ex_svm_2_22.Rnw">>=
	@
}
\dlz

\aufgabe{Kernel Trick}{
	<<child="ex_rnw/ex_kernel_trick.Rnw">>=
	@
}
