% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopfsl{10}{Support Vector Machines}

\aufgabe{SVM -- Regression}{
	<<child="ex_rnw/ex_svm_1_22.Rnw">>=
	@
}
\dlz

\aufgabe{SVM -- Optimization}{
	<<child="ex_rnw/ex_linsvm_subgradient.Rnw">>=
	@
}
