% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopfsl{11}{Nonlinear Support Vector Machines}

\loesung{Kernelized Muliclass SVM}{
	<<child="ex_rnw/sol_svm_2_22.Rnw">>=
	@
}
\dlz

\loesung{Kernel Trick}{
	<<child="ex_rnw/sol_kernel_trick.Rnw">>=
	@
}
