% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopfsl{10}

\loesung{
	<<child="ex_rnw/sol_linsvm_hyperplane.Rnw">>=
	@
}
\dlz

\loesung{
	<<child="ex_rnw/sol_linsvm_subgradient.Rnw">>=
	@
}
