% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopfsl{9}{Support Vector Machines}

\loesung{SVM -- Regression}{
	<<child="ex_rnw/sol_svm_1_22.Rnw">>=
	@
}
\dlz

\loesung{SVM -- Optimization}{
	<<child="ex_rnw/sol_linsvm_subgradient.Rnw">>=
	@
}
