% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\section*{Test exam -- WS2021/22}

\loesung{
<<child="ex_rnw/sol_poly.Rnw">>=
@
}
\dlz

\loesung{
<<child="ex_rnw/sol_roc_island.Rnw">>=
@
}

\dlz

\loesung{
<<child="ex_rnw/sol_knn_gower.Rnw">>=
@
}

\dlz
\loesung{
<<child="ex_rnw/sol_lda_qda.Rnw">>=
@
}
