% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-ensembles.tex}

\kopf{Gradient Boosting}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{Gradient Boosting}{
	<<child="ex_rnw/ex_boosting_exam_2020.Rnw">>=
	@
}

% % ------------------------------------------------------------------------------
% % PAST EXAMS
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exexams
% \lz
% 
% \aufgabeexam{WS2020/21}{first}{1}{
% foo
% }
% 
% \dlz
% \loesung{
% bar
% }
% 
% % ------------------------------------------------------------------------------
% % INSPO
% % ------------------------------------------------------------------------------
% 
% \dlz
% \exinspo