% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
%\input{../../latex-math/basic-boosting.tex}


\kopf{10}


\aufgabe{
<<child="exercises/boosting_a_1.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="exercises/boosting_a_2.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="exercises/boosting_a_3.Rnw">>=
@
}

\dlz
