% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{1}


\aufgabe{
<<child="files_rnw/ex_types_1.Rnw">>=
@
}

\dlz
\aufgabe{
<<child="files_rnw/ex_lin_reg_1.Rnw">>=
@
}

\dlz

\pagebreak[2]

\aufgabe{
<<child="files_rnw/ex_ml_basics_1.Rnw">>=
@
}