---
title: "Exercise 4 -- Classification II"
subtitle: "[Introduction to Machine Learning](https://slds-lmu.github.io/i2ml/)"
notebook-view:
  - notebook: ex_classification_2_R.ipynb
    title: "Exercise sheet for R"
    url: "https://github.com/slds-lmu/lecture_i2ml/blob/master/exercises/supervised-classification/ex_classification_2_R.ipynb"
  - notebook: ex_classification_2_py.ipynb
    title: "Exercise sheet for Python"
    url: "https://github.com/slds-lmu/lecture_i2ml/blob/master/exercises/supervised-classification/ex_classification_2_py.ipynb"
  - notebook: sol_classification_2_R.ipynb
    title: "Solutions for R"
    url: "https://github.com/slds-lmu/lecture_i2ml/blob/master/exercises/supervised-classification/sol_classification_2_R.ipynb"
  - notebook: sol_classification_2_py.ipynb
    title: "Solutions for Python"
    url: "https://github.com/slds-lmu/lecture_i2ml/blob/master/exercises/supervised-classification/sol_classification_2_py.ipynb"
---

::: {.content-hidden when-format="pdf"}
::: {.hidden}
{{< include ../_quarto/latex-math.qmd >}}
:::
{{< include ../_quarto/solution-buttons.qmd >}}
:::

<details> 
<summary>*Hint: Useful libraries*</summary>

::: {.panel-tabset}

### R
{{< embed ex_classification_2_R.ipynb#import echo=true >}}
### Python
{{< embed ex_classification_2_py.ipynb#import echo=true >}}
:::
</details>


## Exercise 1: Naive Bayes

::: {.callout-note title="Learning goals" icon=false}
Compute Naive Bayes predictions by hand
:::

You are given the following table with the target variable `Banana`:

| ID  |  Color   |  Form    |  Origin    |  Banana   |
| --- | -------- | -------- | ---------- | --------- |
| 1   |  yellow  |  oblong  |  imported  |  yes      |
| 2   |  yellow  |  round   |  domestic  |  no       |
| 3   |  yellow  |  oblong  |  imported  |  no       |
| 4   |  brown   |  oblong  |  imported  |  yes      |
| 5   |  brown   |  round   |  domestic  |  no       |
| 6   |  green   |  round   |  imported  |  yes      |
| 7   |  green   |  oblong  |  domestic  |  no       |
| 8   |  red     |  round   |  imported  |  no       |

a) We want to use a Naive Bayes classifier to predict whether a new fruit is a `Banana` or not. Estimate the posterior probability $\hat\pi(\xv_{\ast})$ for a new observation $\xv_{\ast} = (\text{yellow}, \text{round}, \text{imported})$. How would you classify the object?

::: {.content-visible when-profile="solution"}
::: {.indent-1-sol}
<details> 
<summary>**Solution**</summary>

When using the naive Bayes classifier, the features $\xv := (x_\text{Color},x_\text{Form},x_\text{Origin})$ are assumed to be conditionally independent of each other, given the category $y = k \in \{\text{yes}, \text{no}\}$, s.t.

\begin{align*}
\P(\xv ~|~ y = k)
&= \P((x_\text{Color}, x_\text{Form}, x_\text{Origin}) ~|~ y = k) \\
&= \P(x_\text{Color} ~|~ y = k) \cdot \P(x_\text{Form} ~|~ y = k) \cdot \P(x_\text{Origin} ~|~ y = k).
\end{align*}

Recall Bayes' theorem:

$$
\pikx = \postk = \bayesrulek
$$

As the denominator is constant across all classes, the following holds for the posterior probabilities:

\begin{align*}
\pi_{k}(\mathbf{x})
&\propto \underbrace{\pi_{k}\cdot \mathbb{P}(x_\text{Color} ~|~ y = k) \cdot \mathbb{P}(x_\text{Form} ~|~ y = k) \cdot \mathbb{P}(x_\text{Origin} ~|~ y = k)}_{=: \alpha_k(x)} \\
&\iff \exists c \in \mathbb{R}: \pi_{k}(\mathbf{x})= c \cdot \alpha_k(\mathbf{x})
\end{align*}

where $\pik = \P(y = k)$ is the prior probability of class $k$ and $c$ is the normalizing constant.

From this and since the posterior probabilities need to sum up to 1, we know that 

$$
1 = ~ c \cdot \alpha_\text{yes}(\xv) +  c \cdot \alpha_\text{no}(\xv)
~\iff c = \frac{1}{\alpha_\text{yes}(\xv) + \alpha_\text{no}(\xv)}.
$$

This means that, in order to compute $\pi_\text{yes}(\xv)$, the scores $\alpha_\text{yes}(\xv)$ and $\alpha_\text{no}(\xv)$ are needed.

Now we want to estimate for a new fruit the posterior probability $\hat{\pi}_{yes}((\text{yellow}, \text{round}, \text{imported}))$.

Obviously, we do not know the *true* prior probability and the *true* conditional densities. Here -- since the target and the features are categorical -- we use a categorical distribution, i.e., the simplest distribution over a $g$-way event that is fully specified by the individual probabilities for each class (which must of course sum to 1). This is a generalization of the Bernoulli distribution to the multi-class case. We can estimate the distribution parameters via the relative frequencies encountered in the data:

\begin{align*}
\hat{\alpha}_\text{yes}(\mathbf{x}_{\ast})
&= \hat{\pi}_{\text{yes}} \cdot 
\hat{\mathbb{P}}(x_\text{Color} = \text{yellow} ~|~ y = \text{yes}) \cdot 
\hat{\mathbb{P}}(x_\text{Form} = \text{round} ~|~ y = \text{yes}) \cdot 
\hat{\mathbb{P}}(x_\text{Origin} = \text{imp} ~|~ y = \text{yes}) \\
&= \frac{3}{8} \cdot \frac{1}{3} \cdot \frac{1}{3} \cdot 1 = \frac{1}{24} 
\approx 0.042
\end{align*}

\begin{align*}
\hat{\alpha}_\text{no}(\mathbf{x}_{\ast}) 
&= \hat{\pi}_{\text{no}} \cdot 
\hat{\mathbb{P}}(x_\text{Color} = \text{yellow} ~|~ y = \text{no})\cdot 
\hat{\mathbb{P}}(x_\text{Form} = \text{round} ~|~ y = \text{no}) \cdot 
\hat{\mathbb{P}}(x_\text{Origin} = \text{imp} ~|~ y = \text{no}) \\
&= \frac{5}{8} \cdot \frac{2}{5} \cdot \frac{3}{5} \cdot \frac{2}{5} = 
\frac{3}{50} = 0.060
\end{align*}

At this stage we can already see that the predicted label is "no", since $\hat{\alpha}_\text{no}(\xv_{\ast}) = 0.060 > \frac{1}{24} = \hat{\alpha}_\text{yes}(\xv_{\ast})$ -- that is, if we threshold at 0.5 for predicting "yes".

With the above we can compute the posterior probability
$$
\hat{\pi}_\text{yes}(\xv_{\ast}) = \frac{\hat{\alpha}_\text{yes}(
\xv_{\ast})}{\hat{\alpha}_\text{yes}(\xv_{\ast}) + 
\hat{\alpha}_\text{no}(\xv_{\ast})} \approx 0.410 < 0.5
$$

and check our calculations against the corresponding results:

::: {.panel-tabset}
### R
{{< embed sol_classification_2_R.ipynb#naivebayes echo=true >}}
### Python
{{< embed sol_classification_2_py.ipynb#naivebayes echo=true >}}
:::

</details>
:::
:::

b) Assume you have an additional feature `Length` that measures the length in cm. Describe in 1-2 sentences how you would handle this numeric feature with Naive Bayes.

::: {.content-visible when-profile="solution"}
::: {.indent-1-sol}
<details> 
<summary>**Solution**</summary>

Before, we only had categorical features and could use the empirical frequencies as our parameters in a categorical distribution. For the distribution of a numerical feature, given the the category, we need to define a probability distribution with continuous support. A popular choice is to use Gaussian distributions. For example, for the information $x_\text{Length}$ we could assume that 

$$
\P(x_\text{Length} ~|~ y = \text{yes}) \sim \normal(\mu_\text{yes}, 
\sigma^2_\text{yes})$$ and $$\P(x_\text{Length} ~|~ y = \text{no}) \sim 
\normal(\mu_\text{no}, \sigma^2_\text{no})
$$ 

In order to fully specify these normal distributions we need to estimate their parameters $\mu_\text{yes}, \mu_\text{no}, \sigma^2_\text{yes}, \sigma^2_\text{no}$ from the data via the usual estimators (empirical mean and empirical variance with bias correction).

</details>
:::
:::

## Exercise 2: Discriminant analysis

::: {.callout-note title="Learning goals" icon=false}
1) Set up discriminant analysis by hand
2) Make predictions with discriminant analysis
3) Discuss difference between LDA and QDA
:::

```{r, echo=FALSE, fig.height=3, fig.width=3}
suppressWarnings(library(ggplot2))
library(ggplot2)
set.seed(31415)

x1 <- runif(49, 0.1, 1.9)
x2 <- runif(98, 2.1, 5.9)
x3 <- runif(49, 6.1, 7.9)
x4 <- c(1,3,5,7)
x <- c(x1, x2, x3, x4)

y1 <- 2 + rnorm(49, 0, 0.02)
y2 <- 4 + rnorm(98, 0, 0.02)
y3 <- 3 + rnorm(49, 0, 0.02)
y4 <- c(4, 2, 3, 4)
y <- c(y1, y2, y3, y4)

d = data.frame(x, y)

ggplot(data = d, aes(x = x, y = y)) +
  geom_point(alpha = 0.25)
```

The above plot shows $\D = \Dset$, a data set with $n = 200$ observations of a continuous target variable $y$ and a continuous, 1-dimensional feature variable $\xv$. In the following, we aim at predicting $y$ with a machine learning model that takes $\xv$ as input.

a) To prepare the data for classification, we categorize the target variable $y$ in 3 classes and call the transformed target variable $z$, as follows:

   $$
   z^{(i)} = 
   \begin{cases}
    1, &  y^{(i)} \in (-\infty, 2.5] \\
    2, &  y^{(i)} \in (2.5, 3.5] \\
    3, &  y^{(i)} \in (3.5, \infty)
   \end{cases}
   $$
   
   Now we can apply quadratic discriminant analysis (QDA):

::: {.indent-1-subitem}
i. Estimate the class means $\mu_k = \mathbb{E}(\mathbf{x}|z = k)$ for each of the three classes $k \in \{1, 2, 3\}$ visually from the plot. Do not overcomplicate this, a rough estimate is sufficient here.
:::

::: {.content-visible when-profile="solution"}
::: {.indent-2-sol}
<details> 
<summary>**Solution**</summary>
As the data seem to be pretty symmetric conditional on the respective class, we estimate the class means to lie roughly in the middle of the data clusters: $\hat \mu_1 = 1$, $\hat \mu_2 = 7$, $\hat \mu_3 = 4$.
</details>
:::
:::

::: {.indent-1-subitem}
ii. Make a plot that visualizes the different estimated densities per class.
:::

::: {.content-visible when-profile="solution"}
::: {.indent-2-sol}
<details> 
<summary>**Solution**</summary>
We see that the variances in classes 1 and 2 are similar and also much smaller than in class 3. Therefore, the densities could look roughly like this:

::: {.panel-tabset}
### R
{{< embed sol_classification_2_R.ipynb#discriminantanalysis-r echo=true >}}
### Python
{{< embed sol_classification_2_py.ipynb#discriminantanalysis echo=true >}}
:::

</details>
:::
:::

b) 

::: {.indent-1-subitem}
i. How would your plot from ii) change if we used linear discriminant analysis (LDA) instead of QDA? Explain your answer.
:::

::: {.content-visible when-profile="solution"}
::: {.indent-2-sol}
<details> 
<summary>**Solution**</summary>
Since LDA assumes constant variances across all classes (also if this does not reflect the data situation), all densities would have the same shape and only differ in location.
</details>
:::
:::

::: {.indent-1-subitem}
ii. Why is QDA preferable over LDA for this data?
:::

::: {.content-visible when-profile="solution"}
::: {.indent-2-sol}
<details> 
<summary>**Solution**</summary>
As we have already noted, the assumption of equal class variances is not justified here, but LDA is confined to equivariant distributions. Therefore, the more flexible QDA is preferable in this case. Note, however, that the Gaussian distributions both variants of discriminant analysis use might not be perfectly appropriate, as the data seems to be more uniformly distributed (conditional on the classes).
</details>
:::
:::

c) Given are two new observations $\xv_{*1} = -10$ and $\xv_{*2} = 7$. Assuming roughly equal class sizes, state the prediction for QDA and explain how you arrive there.

::: {.content-visible when-profile="solution"}
::: {.indent-1-sol}
<details> 
<summary>**Solution**</summary>
Assuming equal class sizes means it's sufficient to compare the class-wise densities at the two points of interest.
The prediction for $\xv_{\ast 1}$ will probably be $\hat z_{\ast 1} = 3$ because the density of class 3 has much larger variance and will therefore overshoot the density of class 1. For $\xv_{\ast 2}$ the case is clear and we have $\hat z_{\ast 2} = 2$.
</details>
:::
:::

::: {.content-hidden when-profile="a"}

## Exercise 3: Decision boundaries for classification learners
::: {.callout-tip icon=false title="The whole exercise is only for lecture group B!"}
:::

::: {.callout-note title="Learning goals" icon=false}
Get a feeling for decision boundaries produced by LDA/QDA/NB
:::

We will now visualize how well different learners classify the three-class `mlbench::mlbench.cassini` data set.

a) * Generate 1000 points from `cassini` using R or import [`cassini_data.csv`](https://github.com/slds-lmu/lecture_i2ml/blob/master/exercises/data/cassini_data.csv) in Python.
   * Then, perturb the `x.2` dimension with Gaussian noise (mean 0, standard deviation 0.5), and consider the classifiers already introduced in the lecture:
      - LDA (Linear Discriminant Analysis),
      - QDA (Quadratic Discriminant Analysis), and
      - Naive Bayes.
   
   Plot the learners' decision boundaries. Can you spot differences in separation ability?
   
   (Note that logistic regression cannot handle more than two classes and is therefore not listed here.)

::: {.content-visible when-profile="solution"}
::: {.indent-1-sol}
<details> 
<summary>**Solution**</summary>

First, visualize the simulated `cassini` data:

::: {.panel-tabset}
### R
{{< embed sol_classification_2_R.ipynb#decb-vis-r echo=true >}}
### Python
{{< embed sol_classification_2_py.ipynb#decb-vis echo=true >}}
:::

Then, define the learners (and the `task` for `R` ) and train the models:

::: {.panel-tabset}
### R
{{< embed sol_classification_2_R.ipynb#decb-learn echo=true >}}
### Python
{{< embed sol_classification_2_py.ipynb#decb-learn echo=true >}}
:::

Lastly, plot their decision boundaries:

::: {.panel-tabset}
### R
{{< embed sol_classification_2_R.ipynb#decb-plot-r echo=true >}}
### Python
{{< embed sol_classification_2_py.ipynb#decb-plot echo=true >}}
:::

We see how LDA, with its confinement to linear decision boundaries, is not able to classify the data very well. QDA and NB, on the other hand, get the shape of the boundaries right. It also becomes obvious that NB is a quadratic classifier just like QDA - their decision surfaces look pretty much alike.

</details>
:::
:::

:::

::: {.content-hidden when-profile="b"}

## Exercise 4: LDA and QDA as linear/quadratic classifiers
::: {.callout-tip icon=false title="The whole exercise is only for lecture group A!"}
:::

::: {.callout-note title="Learning goals" icon=false}
1. Derive why LDA has a linear decision boundary
2. Derive why QDA has a quadratic decision boundary
3. Connect the covariance assumption to the shape of the boundary
:::

In discriminant analysis we model the class-conditional densities as multivariate Gaussians,
$$
\pdfxyk = \frac{1}{(2\pi)^{p/2} |\Sigma_k|^{1/2}} \exp\left(-\tfrac{1}{2}(\xv - \muk)^\top \Sigma_k^{-1} (\xv - \muk)\right),
$$
and obtain the posterior via Bayes' theorem, $\pikx \propto \pik \, \pdfxyk$ (the denominator $p(\xv)$ is the same for all classes). Since we assign $\xv$ to the class with the largest posterior and $\log$ is strictly increasing, it suffices to compare the **discriminant functions**
$$
\delta_k(\xv) := \log\left(\pik \, \pdfxyk\right).
$$
The decision boundary between two classes $j$ and $k$ is the set of points where they are tied, $\{\xv : \delta_j(\xv) = \delta_k(\xv)\}$. Throughout, we may drop any term that does **not** depend on the class $k$: such terms are identical for all classes and cancel in the difference $\delta_j(\xv) - \delta_k(\xv)$.

a) **LDA** assumes a shared covariance matrix $\Sigma_k = \Sigma$ for all classes. Show that $\delta_k(\xv)$ is affine-linear in $\xv$, i.e. $\delta_k(\xv) = w_{0k} + \xv^\top \boldsymbol{w}_k$ with a scalar intercept $w_{0k} \in \mathbb{R}$ and a coefficient vector $\boldsymbol{w}_k = (w_{1k}, \dots, w_{pk})^\top \in \mathbb{R}^p$, and give $w_{0k}$ and $\boldsymbol{w}_k$. Conclude that the decision boundary between any two classes is a hyperplane.

   <details>
   <summary>*Hint*</summary>

   Expand the quadratic form $(\xv - \muk)^\top \Sigma^{-1} (\xv - \muk)$ and check which of the resulting terms depend on the class $k$.

   </details>

::: {.content-visible when-profile="solution"}
::: {.indent-1-sol}
<details>
<summary>**Solution**</summary>

**Step 1: write out the discriminant function.** By definition and the product rule of the logarithm,
$$
\delta_k(\xv) = \log\left(\pik \, \pdfxyk\right) = \log\pik + \log\pdfxyk.
$$
Plugging in the log of the multivariate Gaussian density,
$$
\log\pdfxyk = -\frac{p}{2}\log(2\pi) - \frac{1}{2}\log|\Sigma_k| - \frac{1}{2}(\xv-\muk)^\top\Sigma_k^{-1}(\xv-\muk),
$$
and using the LDA assumption $\Sigma_k = \Sigma$, we obtain
$$
\delta_k(\xv) = \log\pik \; \underbrace{-\;\frac{p}{2}\log(2\pi)}_{\text{const in } k} \; \underbrace{-\;\frac{1}{2}\log|\Sigma|}_{\text{const in } k} \; -\; \frac{1}{2}(\xv-\muk)^\top\Sigma^{-1}(\xv-\muk).
$$

**Step 2: drop class-independent terms.** Why are we allowed to do this? Recall that we only use the $\delta_k$ to *compare* classes: we predict $\arg\max_k \delta_k(\xv)$, and the decision boundary is where $\delta_j(\xv) = \delta_k(\xv)$. Any term that is the **same for all classes** is therefore irrelevant -- it cancels in the difference $\delta_j - \delta_k$, and adding it to every $\delta_k$ shifts them all equally without changing which one is largest. (It would only matter if we wanted the actual posterior *probability* $\pikx$ as a number, as in the Naive Bayes exercise -- then we would need the normalization over all classes.) The two braced terms above do not depend on $k$ (the $(2\pi)$-term never does; $|\Sigma|$ is shared under LDA), so we absorb them into a constant $\text{const}$.

**Step 3: expand the quadratic form.** Since $\Sigma^{-1}$ is symmetric,
\begin{align*}
(\xv-\muk)^\top\Sigma^{-1}(\xv-\muk)
&= \xv^\top\Sigma^{-1}\xv \;-\; \muk^\top\Sigma^{-1}\xv \;-\; \xv^\top\Sigma^{-1}\muk \;+\; \muk^\top\Sigma^{-1}\muk \\
&= \xv^\top\Sigma^{-1}\xv \;-\; 2\,\muk^\top\Sigma^{-1}\xv \;+\; \muk^\top\Sigma^{-1}\muk,
\end{align*}
where the two mixed terms are equal because each is a scalar and $\left(\muk^\top\Sigma^{-1}\xv\right)^\top = \xv^\top\Sigma^{-1}\muk$. Multiplying by $-\tfrac{1}{2}$,
$$
-\frac{1}{2}(\xv-\muk)^\top\Sigma^{-1}(\xv-\muk) = \underbrace{-\frac{1}{2}\xv^\top\Sigma^{-1}\xv}_{\text{const in } k} \;+\; \muk^\top\Sigma^{-1}\xv \;-\; \frac{1}{2}\muk^\top\Sigma^{-1}\muk.
$$
The term $-\tfrac{1}{2}\xv^\top\Sigma^{-1}\xv$ contains $\xv$ but **not** $k$ (again because $\Sigma$ is shared), so it too is class-independent and drops out. Note the subtlety here: this term *does* depend on $\xv$ -- it is even quadratic in $\xv$ -- but at any fixed $\xv$ it contributes the **same** amount to every $\delta_k(\xv)$, so it cancels just like a constant. It is precisely because the only quadratic-in-$\xv$ term is class-independent under LDA that the discriminant ends up linear (under QDA it is not -- see b)).

**Step 4: collect the $k$-dependent terms.**
$$
\delta_k(\xv) = \underbrace{\log\pik - \frac{1}{2}\muk^\top\Sigma^{-1}\muk}_{=:\, w_{0k}} \;+\; \xv^\top\underbrace{\Sigma^{-1}\muk}_{=:\, \boldsymbol{w}_k} \;=\; w_{0k} + \xv^\top\boldsymbol{w}_k,
$$
using once more $\muk^\top\Sigma^{-1}\xv = \xv^\top\Sigma^{-1}\muk$. Here $w_{0k}$ is the scalar **intercept**, while
$$
\boldsymbol{w}_k = (w_{1k}, w_{2k}, \dots, w_{pk})^\top = \Sigma^{-1}\muk
$$
is the vector collecting the $p$ feature coefficients (so $w_{1k}$ is the coefficient of $x_1$, etc.). Each discriminant $\delta_k$ is thus **affine-linear** in $\xv$.

**Step 5: the decision boundary.** Two classes $j, k$ are tied where their discriminants are equal:
$$
\delta_j(\xv) = \delta_k(\xv)
\;\Longleftrightarrow\;
(w_{0j} - w_{0k}) + \xv^\top(\boldsymbol{w}_j - \boldsymbol{w}_k) = 0.
$$
This has the form $b + \xv^\top\boldsymbol{v} = 0$ with $b = w_{0j}-w_{0k}$ and $\boldsymbol{v} = \boldsymbol{w}_j - \boldsymbol{w}_k$ -- a single **linear** equation, i.e. a hyperplane. LDA is therefore a linear classifier.

</details>
:::
:::

b) **QDA** drops this assumption: each class keeps its own covariance matrix $\Sigma_k$. Show that $\delta_k(\xv)$ now contains a term $-\tfrac{1}{2}\xv^\top \Sigma_k^{-1}\xv$ that depends on the class, so that $\delta_k$ is quadratic in $\xv$ and the decision boundary is a curved (quadratic) surface.

::: {.content-visible when-profile="solution"}
::: {.indent-1-sol}
<details>
<summary>**Solution**</summary>

**Step 1: keep each $\Sigma_k$.** The computation runs exactly as in a) up to the point where we invoked the shared covariance. The only term we may still drop is the class-independent $-\tfrac{p}{2}\log(2\pi)$:
$$
\delta_k(\xv) = \log\pik - \frac{1}{2}\log|\Sigma_k| - \frac{1}{2}(\xv-\muk)^\top\Sigma_k^{-1}(\xv-\muk) + \text{const}.
$$
Note that the normalizer $-\tfrac{1}{2}\log|\Sigma_k|$ now **does** depend on $k$ (different $\Sigma_k$), so -- unlike in a) -- we must keep it.

**Step 2: expand the quadratic form** just as in a), but with $\Sigma_k$ in place of $\Sigma$:
$$
\delta_k(\xv) = \log\pik - \frac{1}{2}\log|\Sigma_k| \;\underbrace{-\;\frac{1}{2}\xv^\top\Sigma_k^{-1}\xv}_{\text{depends on } k\,!} \;+\; \muk^\top\Sigma_k^{-1}\xv \;-\; \frac{1}{2}\muk^\top\Sigma_k^{-1}\muk + \text{const}.
$$

**Step 3: the quadratic term survives.** The decisive difference to a) is the term $-\tfrac{1}{2}\xv^\top\Sigma_k^{-1}\xv$: it now carries the class index $k$ (because the $\Sigma_k$ differ), so it no longer cancels between classes. Hence $\delta_k$ is a genuine **quadratic** function of $\xv$.

**Step 4: the decision boundary.** Forming the difference for two classes $j, k$ (the linear term of class $k$ is $\muk^\top\Sigma_k^{-1}\xv = (\Sigma_k^{-1}\muk)^\top\xv$),
$$
\delta_j(\xv) - \delta_k(\xv) = -\frac{1}{2}\,\xv^\top\left(\Sigma_j^{-1} - \Sigma_k^{-1}\right)\xv + \left(\Sigma_j^{-1}\muk[j] - \Sigma_k^{-1}\muk\right)^\top\xv + \text{const} = 0.
$$
Because of the leading term $\xv^\top(\Sigma_j^{-1}-\Sigma_k^{-1})\xv$, this is a **quadratic** equation in $\xv$, describing a curved surface (in 2D a conic section -- ellipse, parabola, or hyperbola). Only if $\Sigma_j = \Sigma_k$ for all classes does $\Sigma_j^{-1} - \Sigma_k^{-1} = \mathbf{0}$, the quadratic term vanishes, and we recover the linear boundary of a) -- i.e. LDA is exactly the special case of QDA with equal covariances.

</details>
:::
:::

c) Finally, we examine the cost of QDA's flexibility and how Naive Bayes relates to LDA and QDA.

::: {.indent-1-subitem}
i. Recall which modeling assumption distinguishes QDA from LDA. Based on this, what does QDA have to estimate from the data that LDA does not, and how many additional free parameters does this require? What practical disadvantage for QDA follows?
:::

::: {.content-visible when-profile="solution"}
::: {.indent-2-sol}
<details>
<summary>**Solution**</summary>

The distinguishing assumption is the covariance structure: LDA assumes one **shared** $\Sigma$, QDA allows each class its **own** $\Sigma_k$. So QDA must estimate $g$ separate covariance matrices, whereas LDA estimates only a single shared one. A covariance matrix is a symmetric $p\times p$ matrix; it is fully determined by its $p$ diagonal entries plus the $\tfrac{p(p-1)}{2}$ entries above the diagonal, i.e. $p + \tfrac{p(p-1)}{2} = \tfrac{p(p+1)}{2}$ free parameters. Hence QDA spends $g \cdot \tfrac{p(p+1)}{2}$ such parameters against LDA's $\tfrac{p(p+1)}{2}$. The practical disadvantage: QDA needs considerably more data to estimate all these parameters reliably and overfits more easily when the classes are small.

</details>
:::
:::

::: {.indent-1-subitem}
ii. In Exercise 1, Naive Bayes assumed the features to be conditionally independent given the class. For **numeric** features modeled by Gaussians, this makes Gaussian Naive Bayes a special case of QDA. What does the independence assumption imply for the covariance matrices $\Sigma_k$, and how does the shape of the class densities (and hence the decision boundary) then compare to a *general* QDA?

<details>
<summary>*Hint*</summary>

Recall what the off-diagonal entries of a covariance matrix encode.

</details>
:::

::: {.content-visible when-profile="solution"}
::: {.indent-2-sol}
<details>
<summary>**Solution**</summary>

Conditional independence of the features given the class means the joint class-conditional density factorizes,
$$
\pdfxyk = \prod_{j=1}^p p(x_j \mid y = k).
$$
For Gaussian features this forces each $\Sigma_k$ to be **diagonal**: the off-diagonal entries encode the pairwise feature covariances, which independence sets to zero. The diagonal entries may still differ across features (non-isotropic) and across classes, so Gaussian Naive Bayes is exactly **QDA with diagonal covariance matrices**.

*Geometric interpretation.* The contours of a Gaussian density are ellipses whose axes point along the eigenvectors of $\Sigma_k$. For a **diagonal** $\Sigma_k$ these eigenvectors are the coordinate axes, so NB's class densities are **axis-aligned** ellipses -- stretched differently along each feature axis, but never **tilted**. A general QDA, with full $\Sigma_k$, allows **rotated** ellipses that capture correlations between features. Both still produce quadratic decision boundaries (the class-dependent $-\tfrac{1}{2}\xv^\top\Sigma_k^{-1}\xv$ term survives), but a diagonal $\Sigma_k^{-1}$ leaves **no $x_i x_j$ cross-terms**, so NB's conic boundaries stay axis-aligned, whereas a general QDA's can be tilted. This is why NB and QDA "look alike" (both curved) and yet NB is the more constrained model.

</details>
:::
:::

:::
