% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{3}

\aufgabe{
<<child="ex_rnw/ex_softmax.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="ex_rnw/ex_logreg_dec_boundaries_enhanced.Rnw">>=
@
}

\dlz

\aufgabe{
<<child="ex_rnw/ex_mlr_dec_boundaries.Rnw">>=
@
}