% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{4}


\aufgabe{Naive Bayes}{
<<child="ex_rnw/ex_naive_bayes.Rnw">>=
@
}

\dlz


\aufgabe{Discriminant Analysis}{
<<child="ex_rnw/ex_lda_qda.Rnw">>=
@
}


\dlz

\aufgabe{Decision Boundaries for \texttt{mlr3} Learners}{
<<child="ex_rnw/ex_mlr_dec_boundaries.Rnw">>=
@
}

