% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{4}


\aufgabe{
<<child="exercises/knn_manh_a_1.Rnw">>=
@
}

\dlz


\aufgabe{
<<child="exercises/lrn_a_1.Rnw">>=
@
}

\dlz

\pagebreak[2]

\aufgabe{
<<child="exercises/lm_knn_a_1.Rnw">>=
@
}

\dlz
