% !Rnw weave = knitr

<<setup-child, include=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{4}

\dlz
\loesung{
<<child="ex_rnw/sol_naive_bayes.Rnw">>=
@
}

\newpage

\dlz
\loesung{
<<child="ex_rnw/sol_lda_qda.Rnw">>=
@
}

\loesung{

See \href{https://github.com/slds-lmu/lecture_i2ml/blob/master/exercises/supervised-classification/ex_rnw/sol_mlr_dec_boundaries.R}{R code}
}
