% !Rnw weave = knitr

<<setup-child, include=FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}

\kopf{4}



\loesung{
See R code \href{https://github.com/compstat-lmu/lecture_i2ml/blob/master/exercises/supervised-classification/mlr_dec_boundaries_a_1.Rnw}{\textbf{mlr\_dec\_boundaries\_a\_1.R}}
}

\dlz


\aufgabe{
<<child="knn_manh_l_1.Rnw">>=
@
}

\dlz


\loesung{
<<child="naive_bayes_l_1.Rnw">>=
@
}


