Let $i = 1,\dots,n$ and $y^{(i)} \in \mathbb{R}$ be the ordered data of interest. Show that the median, which is then given by $$ y_{\text{med}} = \begin{cases}
\frac{y^{(\frac{n}{2})} +  y^{(\frac{n}{2} + 1 )}}{2},& \text{ if } n \text{ is even }  \\
 y^{(\frac{n+1}{2} )},& \text{ if } n \text{ is odd }
\end{cases}, $$ is the best constant model with L1 loss. \\
\textit{Hint}: 
Rearrange and combine terms of the empirical risk $\riske$ associated to the L1 loss $L$ into new summands, s.t.
you can use the fact that
for $a,b \in \mathbb{R}, S_{a,b}:\mathbb{R} \rightarrow \mathbb{R}^+_0, c \mapsto |a-c| + |b-c|$ it holds that $c^* \in [a,b]$ minimizes $S_{a,b}$, to show that $y_{\text{med}}$ minimizes each of these summands newly formed.