\begin{enumerate}
  \item[a)] multiclass classification (plate digits) (supervised learning)
  \item[b)] binary classification (supervised)
  \item[c)] outlier detection ((un)supervised)
  \item[d)] frequent pattern mining (unsupervised)
  \item[e)] classification (supervised) / clustering (unsupervised)
  \item[f)] classification (supervised)
  \item[g)] clustering / assocation rules (unsupervised)
  \item[h)] not a machine learning task
  \item[i)] not a machine learning task
\end{enumerate}