% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-svm.tex}
\input{../../latex-math/ml-gp.tex}

\kopficsl{10}{Gaussian Processes}



\aufgabe{Gaussian Processes - Covariance Function}{
	<<child="ex_rnw/ic_gp_1.Rnw">>=
	@
}
