% !Rnw weave = knitr

<<setup-child, include = FALSE, echo=FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb_coll.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{CART}

\tableofcontents

% ------------------------------------------------------------------------------
% LECTURE EXERCISES
% ------------------------------------------------------------------------------

\dlz
\exlect
\lz

\aufgabe{bagging and correlation}{
<<child="ex_rnw/ex_bagging.Rnw">>=
@
}

\dlz
\loesung{
<<child="ex_rnw/sol_bagging.Rnw">>=
@
}

\aufgabe{split computation}{
<<child="ex_rnw/ex_trees_1.Rnw">>=
@
}

\dlz
\loesung{
<<child="ex_rnw/sol_trees_1.Rnw">>=
@
}

\aufgabe{lymphography classification}{
<<child="ex_rnw/ex_trees_2.Rnw">>=
@
}

\dlz
\loesung{

See 
\href{https://github.com/compstat-lmu/lecture_i2ml/blob/master/exercises/trees/ex_rnw/sol_trees_2.R}{R code}
}


\newpage

\aufgabe{leaf node prediction}{
<<child="ex_rnw/ex_trees_3.Rnw">>=
@
}

\dlz
\loesung{
<<child="ex_rnw/sol_trees_3.Rnw">>=
@
}

% ------------------------------------------------------------------------------
% PAST EXAMS
% ------------------------------------------------------------------------------

\dlz
\exexams
\lz

\aufgabeexam{WS2020/21}{retry}{1}{}

% ------------------------------------------------------------------------------
% INSPO
% ------------------------------------------------------------------------------

\dlz
\exinspo