
<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}


\kopf{6}


\aufgabe{
	<<child="exercises/trees_a_0.Rnw">>=
	@
}


\dlz

\aufgabe{
	<<child="exercises/trees_a_1.Rnw">>=
	@
}


\dlz


\aufgabe{
	<<child="exercises/trees_a_2.Rnw">>=
	@
}

\dlz
