You want to estimate the relationship between a continuous response variable $\bm{y} \in \mathbb{R}^n$ and some features $\bm{X} \in \mathbb{R}^{n \times p}$ using the linear model with an appropriate loss function $L$.

\begin{enumerate}
  \item Describe the model $f$ used in this case, its hypothesis space $\mathcal{H}$ and the theoretical risk function.
  \item Given $f \in \mathcal{H}$, explain the different parts of the Bayes regret if (i) $f^\ast \in \mathcal{H}$; if (ii) $f^\ast \notin \mathcal{H}$.
  \item Define the empirical risk and derive the gradients of the empirical risk.
  \item Show that the empirical risk is convex in the model coefficients. Why is convexity a desirable property? Hint: Compute the Hessian matrix $\bm{H} \in \mathbb{R}^{p \times p}$ and show that $\bm{z}^\top \bm{H} \bm{z} \geq 0 \, \forall \bm{z} \in \mathbb{R}^p$, i.e., show that the Hessian is positive semi-definite (psd).  
\end{enumerate}