Chapter 1 of the lecture introduces many important machine learning concepts. Within your group, go through the lecture slides and identify one such concept. Try to explain the main idea in your own words as good as possible. Afterwards, add your results to the shared mural whiteboard, including the following information:

\begin{enumerate}[a)]
  \item Group Name (e.g. your favorite animal)
  \item Name of the concept
  \item A few bullet points explaining the main idea
\end{enumerate}

The link to the mural whiteboard can be found in this week's etherpad. Select a group member who can present your concept shortly in class after the end of the group work.