% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}


\kopf{11}{Nested Resampling}

\aufgabe{Tuning Principles}{
	<<child="ex_rnw/ex_cart_vs_knn.Rnw">>=
	@
}

\newpage
\dlz
\aufgabe{AutoML}{
<<child="ex_rnw/ex_automl.Rnw">>=
@
}

\dlz
\aufgabe{Kaggle Challenge}{
<<child="ex_rnw/ex_kaggle.Rnw">>=
@
}
