% Introduction to Machine Learning
% Day 3

% Set style/preamble.Rnw as parent.
<<set-parent, include = FALSE>>=
knitr::set_parent("../style/preamble.Rnw")
@

% Load all R packages and set up knitr
<<setup, child="../style/setup.Rnw", include = FALSE>>=
@


\lecturechapter{10}{Confidence Intervals for the Test Error}
\lecture{Introduction to Machine Learning}

\begin{vbframe}{Test Error Confidence Intervals}
\begin{itemize}
  \item In the last chapter we have seen different approaches to getting a better point estimate of 
  the error our model has on unseen data using the expected generalization error 
  \item A confidence interval on this test error can provide us with more information than just a point estimate
  \item This confidence interval can be estimated in two ways:
  \begin{itemize}
    \item nonparametric confidence interval using resampling
    \item parametric confidence interval for classification error
  \end{itemize}
\end{itemize}
 
\framebreak

Nonparametric confidence interval using resampling:

\begin{itemize}
  \item As in the previous lecture\\
  Repeat n times:
  \begin{itemize}
    \item[1.] Get a sample using resampling (e.\ g.\ bootstrapping)
    \item[2.] Fit a model on the sample
    \item[3.] Get the test error of the model on data not included in the sample
  \end{itemize}
  \item Of the resulting n test errors, the 2.5~\%-quantile and the 97.5~\%-quantile 
  provide an estimate for a 95~\% confidence interval: $\left[Q_{2.5 \%}, Q_{97.5 \%}\right]$
\end{itemize}
 
\framebreak

Parametric confidence interval for the classification error:

\begin{itemize}
  \item The error of the prediction for each instance of the sample is a binary random variable (correct/incorrect)
  and hence represents a Bernoulli trial
  \item The classification error of the whole sample follows a Binomial distribution as it 
  is based on a sequence of Bernoulli trials
  \item The variance of a Binomial trial can be calculated by $np(1-p)$ where $p$ is the classification error 
  and $n$ the number of trials, i. e., the sample size
  \item The binomial distribution can be approximated by the Gaussian distribution for large $n$ (at least 30)
  \item Therefore, a $1-\alpha$ \%~confidence interval for an accuracy $p$ can be calculated as: 
  $\left[p \pm z_{1-\frac{\alpha}{2}} \frac{\sqrt{np \left(1-p\right)}}{n} \right]$

\end{itemize}



\end{vbframe}
\endlecture