\begin{enumerate}
\item What is the relationship between the softmax 
$$\pi_i(\xb)=\frac{\exp\{\boldsymbol{\theta}_i^T \xb\}}{\sum_k \exp\{\boldsymbol{\theta}_k^T \xb\}}$$ and the logistic function $$\pi(\xb)=\frac{1}{1+\exp\{\boldsymbol{\theta}^{T} \xb\}}$$? 

\item Derive the negative log-likelihood of a softmax regression assuming that the outcome follows a multinomial distribution with $g$ classes.

\end{enumerate}