\begin{enumerate}
\item What is the relationship between the softmax 
$$\pi_i(\xv)=\frac{\exp\{\boldsymbol{\theta}_i^T \xv\}}{\sum_k \exp\{\boldsymbol{\theta}_k^T \xv\}}$$ and the logistic function $$\pi(\xv)=\frac{1}{1+\exp\{\boldsymbol{\theta}^{T} \xv\}}$$? 

\item Derive the negative log-likelihood of a softmax regression assuming that the outcome follows a multinomial distribution with $g$ classes.

\end{enumerate}