The polynomial kernel is defined as
$$
k(x, \tilde{x}) = (x^T\tilde{x} + b)^d.
$$
Furthermore, assume $x \in \mathbb{R}^2$ and $d = 2$.

\begin{enumerate}

  \item
    Derive the explicit feature map $\phi$ taking into account that the following equation holds:
    $$
    k(x, \tilde{x}) = \langle \phi(x), \phi(\tilde{x}) \rangle
    $$

  \item
    Describe the main differences between the kernel method and the explicit feature map.

\end{enumerate}
