Write your own stochastic subgradient descent routine to solve the soft-margin SVM in the primal formulation.\\

Hints:
\begin{itemize}
\item Use the regularized-empirical-risk-minimization formulation, i.e., an optimization criterion without constraints.
\item No kernels, just a linear SVM.
\item Compare your implementation with an existing implementation (e.g., \texttt{kernlab} in R). Are your results similar? Note that you might have to switch off the automatic data scaling in the already existing implementation.
\end{itemize}
