
SLOT1=slides-tuning
SLOT2=slides-practical

all: $(SLOT1).pdf $(SLOT2).pdf 

$(SLOT1).pdf: $(SLOT1).Rnw
	Rscript -e 'knitr::knit2pdf("$(SLOT1).Rnw")'

$(SLOT2).pdf: $(SLOT2).Rnw
	Rscript -e 'knitr::knit2pdf("$(SLOT2).Rnw")'

