With $\thetab := (\theta_0, \theta_1, \theta_2, 
\theta_3, \theta_4, \theta_5)^\top$, we have

\begin{align*}
\Hspace &= \{ \fxt = \theta_0 + \theta_1 x + \tfrac{1}{2}\theta_2 x^2 + 
\tfrac{1}{3}\theta_3 x^3 + \tfrac{1}{4}\theta_4 x^4 + 
\tfrac{1}{2 \cdot 4} \theta_5 x^2 x^4 ~|~ \thetab \in \R\} \\
&= \{ \fxt = \theta_0 + \theta_1 x + \tfrac{1}{2}\theta_2 x^2 + 
\tfrac{1}{3}\theta_3 x^3 + \tfrac{1}{4}\theta_4 x^4 + 
\tfrac{1}{8} \theta_5 x^6 \}
\end{align*}
