
The following data set contains $n = 13$ datapoints, the triangles denote class $+1$ and the circles denote class $-1.$

\begin{figure}[h!]
\centering
<<echo = FALSE, fig.height = 3, fig.width = 4>>=
library(ggplot2)
library(gridExtra)
data = data.frame(
  x1 = c(1  , 1.5, 1.7, 2  , 2.2, 2.4, 2.6, 2.4,    2.6, 2.8, 3, 1.7, 3.3) -1,
  x2 = c(1.5, 1.9, 0.8, 1.2, 2.1, 1.7, 1.1, 2.6,   2.7, 2.3, 2.5, 2.6, 1.3) -0.8,
  y = as.factor(c(rep(-1,8),c(1,1),rep(-1,3))))

p = ggplot(data = data) + geom_point(aes(x = x1, y = x2, shape = y, color = y), size = 4) +
  theme_minimal() + xlim(0,2.5) + ylim(0, 2) + theme(legend.position = "none") + coord_fixed()

p

@
\end{figure}


\begin{enumerate}
	%	
	\item Let $f(\xv) = 2 \cdot \mathds{1}_{[  \thetab^\top \xv \ge 3]} -1 $ with $\thetab=(1,1)^\top.$ Specify the confusion matrix of $f$ and compute its accuracy as well as its $F_1$ score.
	%
	\item Find all Tomek links with respect to the Euclidean distance on $\Xspace$ in the data set and remove the instances in each Tomek link belonging to the majority class. Repeat the computation in (a).  
	%	
	\item What is the accuracy of the classifier $f_-(\xv) = -1$ before  and after removing the Tomek links?
	%
\end{enumerate}