Consider a multi-label classification task with $m=4$ targets 
%$\mathcal{T} = \{ \texttt{BEACH}, \texttt{FOREST}, \texttt{MOUNTAIN}, \texttt{SEA} \}$ 
and suppose that the conditional distribution of the score $\yv=(y_1,y_2,y_3,y_4)$ for any feature instance $\xv\in \Xspace$ is given as follows


\begin{center}
	\begin{tabular}{@{}c|c@{}}
		$\yv=(y_1,y_2,y_3,y_4)$ & $\P(\yv ~|~ \xv)$ \\
		\hline
		$0~0~0~0$ & $3/12$ \\
		$0~1~1~1$ & $1/12$ \\
		$1~0~1~1$ & $2/12$ \\
		$1~1~0~1$ & $2/12$ \\
		$1~1~1~0$ & $2/12$ \\
		$1~1~1~1$ & $2/12$ \\
	\end{tabular}
\end{center}
% 
\begin{enumerate}
	%	
	\item Show that the individual target score variables are not independent.
	%
	\item What is the risk minimizer (Bayes predictor) $\fbayes$ for Hamming loss and subset 0/1 loss in this case, respectively?
	%	
	\item Specify a condition on the conditional distribution of the score so that the risk minimizer for Hamming loss and subset 0/1 loss coincide.
	%
\end{enumerate}