Which of the following statements are correct and which are not? In each case, give also a brief explanation (1--2 sentences).
%
\begin{enumerate}
	%	
	\item Removing a sensitive attribute/feature at prediction (or decision) time might not ensure that fair decisions will be made.
	%
	\item Separation is a posthoc (fairness) criterion.
	%
	\item MetaCost can only be used for probabilistic classifiers.
	%
	\item  The appealing property of SMOTE is that it takes the entire data space $\Xspace \times \Yspace$ into account for creating a new synthetic example of a minority class.
%	
	\item  The maximum-likelihood estimate for the mean of random observations following a multivariate Gaussian distribution is always optimal in terms of the mean-squared error.
%	
	\item The key difference between batch and online learning is that in the former the training and testing phase are decoupled, while in the latter the two phases are intertwined.
%	
	\item The regret of the FTL algorithm is linearly growing with respect to the time horizon $T$ on every online linear optimization problem. 
	%
\end{enumerate}