Consider a multi-label classification task with $m=4$ targets 
%$\mathcal{T} = \{ \texttt{BEACH}, \texttt{FOREST}, \texttt{MOUNTAIN}, \texttt{SEA} \}$ 
and suppose that the conditional distribution of the score $\yv=(y_1,y_2,y_3,y_4)$ for any feature instance $\xv\in \Xspace$ is given as follows


\begin{center}
	\begin{tabular}{@{}c|c@{}}
		$\yv=(y_1,y_2,y_3,y_4)$ & $\P(\yv ~|~ \xv)$ \\
		\hline
		$0~0~0~0$ & $3/12$ \\
		$0~1~1~1$ & $1/12$ \\
		$1~0~1~1$ & $2/12$ \\
		$1~1~0~1$ & $2/12$ \\
		$1~1~1~0$ & $2/12$ \\
		$1~1~1~1$ & $2/12$ \\
	\end{tabular}
\end{center}
% 
\begin{enumerate}
	%	
	\item Show that the individual target score variables are not independent.
	
 	\item[]	{\color{blue} \textbf{Solution:}   
		%	
		\begin{align*}
%			
			\P(y_1 = 1) \P(y_2 = 1) &=  8/12 \cdot 7/12 = 56/144 \neq 1/2 = 6/12 = \P(y_1 = 1,y_2 = 1) 
%			
		\end{align*}
		%		
	} 
	%
	\item What is the risk minimizer (Bayes predictor) $\fbayes$ for Hamming loss and subset 0/1 loss in this case, respectively?
	%	
	
 	\item[]	{\color{blue} \textbf{Solution:}   
		%	
		The risk minimizer for the Hamming loss is the marginal mode, which is in this case
%		
		\begin{align*}
			%			
				\fbayes_{Ham}(\xv) = (1,1,1,1)^\top.
			%			
		\end{align*}
		%		
		The risk minimizer for the subset 0/1 loss is the joint mode, which is in this case
		%		
		\begin{align*}
			%			
			\fbayes_{0/1}(\xv) = (0,0,0,0)^\top.
			%			
		\end{align*}
	} 

	\item Specify a condition on the conditional distribution of the score so that the risk minimizer for Hamming loss and subset 0/1 loss coincide.
	
 	\item[]	{\color{blue} \textbf{Solution:}   
		%	
		If the individual target score variables are (conditionally) independent, i.e., $\P(\yv~|~\xv) = \prod_{j=1}^m \P(y_j~|~\xv),$ both risk minimizer would coincide:
		%		
		\begin{align*}
			%			
			\fbayes_{0/1}(\xv) 
%			
			&= \argmax_{\yv \in \Yspace^m} \P(\yv~|~\xv) \\
			%			
			&= \argmax_{(y_1,\ldots,y_m) \in \Yspace^m} \prod_{j=1}^m \P(y_j~|~\xv) \\
			%			
			&= \left( \argmax_{y_1 \in \Yspace} \P(y_1~|~\xv),\ldots, \argmax_{y_m \in \Yspace} \P(y_m~|~\xv) \right) \\
%			
			&= \fbayes_{Ham}(\xv)
			%			
		\end{align*}
		%		
	} 
	%
\end{enumerate}