	
	\newcommand{\sens}{\mathbf{A}} % vector x (bold)
	\newcommand{\ba}{\mathbf{a}}
	\newcommand{\batilde}{\tilde{\mathbf{a}}}
	\newcommand{\Px}{\mathbb{P}_{x}} % P_x
	\newcommand{\Pxj}{\mathbb{P}_{x_j}} % P_{x_j}
	\newcommand{\indep}{\perp \!\!\! \perp} % independence symbol
	
%
\begin{enumerate}
%	
	\item  Assume that the sensitive attribute $\sens$ has only two possible realizations $\ba$ and $\batilde.$ Further, assume that the joint distribution of the (binary) label $y$ and the sensitive attribute $\sens$ is given as follows
%	
	
	\begin{center}
%		
		\begin{tabular}{c||c|c}
			& $\sens = \ba$ &  $\sens = \batilde$ \\
			\hline\hline
			 & &  \\
			$y=-1$ & 1/4 & 1/4 \\
			& &  \\
			\hline
			& &  \\
			$y=+1$	& 1/4 & 1/4 \\
			& &  
		\end{tabular}
%		
	\end{center}
	
	Specify a distribution $\P(\sens,y,\yh)$ such that the following holds:
%	
	\begin{itemize}
%		
		\item [(i)] the marginal distribution $\P(\sens,y)$ is the same as in the table above;
%		
		\item [(ii)] the independence fairness criterion is fulfilled;
%		
		\item [(iii)] $\yh$ has an accuracy of 1.
%		
	\end{itemize}
%
	For this purpose, use the following table
%	
	\begin{center}
%		
		\begin{tabular}{c||c|c|c|c}
%			
			& \multicolumn{2}{c|}{$\sens = \ba$} &  \multicolumn{2}{c}{$\sens = \batilde$}  \\
			\hline
			\hline
			& & &  &  \\
			$y=-1$  & {\color{blue} 0}  & {\color{blue} 1/4} & {\color{blue} 0} & {\color{blue} 1/4} \\
			  & & &  &  \\
			\hline
			& & &  &  \\
			$y=+1$  & {\color{blue} 1/4} & {\color{blue} 0} & {\color{blue} 1/4}  & {\color{blue} 0}  \\
			& & &  &  \\
			\hline
			\hline
			& $\yh=+1$ & $\yh=-1$ & $\yh=+1$ & $\yh=-1$  
		\end{tabular}
%		
	\end{center}

	Justify that the conditions (i)--(iii) are satisfied for the specified joint distribution.
	
	{\color{blue} \textbf{Solution:}   
%	
	\begin{itemize}
		%		
		\item [(i)] the marginal distribution $\P(\sens,y)$ of the above distribution is obtained by summing over the entries $\yh=+1$ and  $\yh=-1,$ respectively. Then, it is obvious that the marginal distribution $\P(\sens,y)$ is the same as above.
		%		
		\item [(ii)] For any $l\in\{-1,1\}$ and any $\check{\ba} \in \{\ba,\batilde\}$ it holds that 
%		
		$$	\P(\yh = l, \sens = \check{\ba}) = 1/4  = 1/2 \cdot 1/2 = \P(\yh = l) \P(\sens = \check{\ba}),		$$
%		
		so that the independence criterion is fulfilled.
		%		
		\item [(iii)] The accuracy of $\yh$ is one:
%		
		$$	\rho_{ACC} = 1 - \P(\yh \neq y) = 1- 0 = 1.	$$
		%		
	\end{itemize}
%
	}
	
%	
	\item Let $f:\Xspace \to \Yspace$ be a score-based (binary) classifier and let its score random variable be $\mathbf{S}.$ Suppose that $f$ satisfies the sufficiency fairness criterion, i.e., for
	all possible realizations $\ba,\batilde$ of $\sens$ and all possible scores $s$ it holds that
	%			
	\begin{align*}
		&\P(  y = 1 ~|~ \mathbf{S} = s, \sens = \ba ) = \P(  y = 1 ~|~  \mathbf{S} = s, \sens = \batilde ).
	\end{align*}
%	
	 Show that the classifier $\tilde f$ with score random variable $C(\mathbf{S}),$ where $C(s) = \P(y=1 ~|~ \mathbf{S} = s, \sens = \batilde )$ for some fixed realization $\batilde$ of $\sens$ is calibrated on the group level, i.e., for all $s\in[0,1]$ and all possible realizations $\ba$ of $\sens$ it holds that
	 %			
	 $$  \P(  y = 1 ~|~ C(\mathbf{S}) = s, \sens = \ba  ) = s. $$
	 
 	{\color{blue} \textbf{Solution:}   
	 	%	
	 	Since $\mathbf{S}$ satisfies sufficiency, it holds that $C(s) = \P( y = 1 ~|~ \mathbf{S} = s, \sens = \batilde ) = \P(  y = 1 ~|~ \mathbf{S} = s, \sens = \ba )$ for all possible  realizations $\ba$ of $\sens.$
%	 	
		With this,
%		
		\begin{align*}
%			
			s  	&=  \P( y = 1 ~|~ C(\mathbf{S}) = s, \sens = \batilde ) \\
%			
				&=	 \P( y = 1 ~|~ \mathbf{S} = C^{-1}(s), \sens = \batilde ) \\
				%			
				&=	 \P( y = 1 ~|~ \mathbf{S} = C^{-1}(s), \sens = \ba ) \\
				%			
				&=	 \P( y = 1 ~|~ C(\mathbf{S}) = s,\sens = \ba ).
%			
		\end{align*}
	 	%
	 } 
%	
\end{enumerate}