<<setup-child, include = FALSE>>=
library('knitr')
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\kopf{4}

\aufgabe{
	<<child="../single-exercises/randomForest_a_0.Rnw">>=
	@
}


\aufgabe{
	<<child="../single-exercises/randomForest_a_2.Rnw">>=
	@
}	

\dlz	

\aufgabe{
	<<child="../single-exercises/trees_a_0.Rnw">>=
	@
}	


\dlz	


\aufgabe{
	<<child="../single-exercises/trees_a_2.Rnw">>=
	@
}	

\dlz	


\aufgabe{
	<<child="../single-exercises/bagging_a_1.Rnw">>=
	@
}





