---
title: "Exercise 1 -- ML Basics"
subtitle: "[Introduction to Machine Learning](https://slds-lmu.github.io/i2ml/)"
notebook-view:
  - notebook: _r.ipynb
    title: "Notebook for R"
    url: "https://github.com/slds-lmu/lecture_i2ml/blob/new-ex-regr-quarto/exercises/supervised-regression-quarto/_r.ipynb"  
  - notebook: _python.ipynb
    title: "Notebook for Python"
    url: "https://github.com/slds-lmu/lecture_i2ml/blob/new-ex-regr-quarto/exercises/supervised-regression-quarto/_python.ipynb"  

---

::: {.content-hidden when-format="pdf"}
::: {.hidden}
{{< include ../_quarto/latex-math.qmd >}}
:::
:::

## Exercise 1: HRO in coding frameworks

::: {.callout-note title="Learning goals" icon=false}
TBD
:::

Throughout the lecture, we will frequently use the `R` package 
`mlr3`, resp. the `Python` package 
`sklearn`, and its descendants, providing an integrated ecosystem for all 
common machine learning tasks.
Let's recap the HRO principle and see how it is reflected in either `mlr3` or `sklearn`.
An overview of the most important objects and their usage, illustrated with 
numerous examples, can be found at [the `mlr3` book](https://mlr3book.mlr-org.com/) and
[the `scikit` documentation](https://scikit-learn.org/stable/index.html).

***
Have a look at`mlr3::tsk("iris")` / `sklearn.datasets.load_iris`. What attributes does this object store?

::: {.content-visible when-profile="solution"}
<details> 
<summary>**Solution**</summary>
::: {.panel-tabset}
### R
{{< embed _r.ipynb#hro-task echo=true >}}
### Python
{{< embed _python.ipynb#hro-task echo=true >}}
:::
</details> 
:::

***

::: {.callout-tip icon=false title="Only for lecture group A"}
:::

Instantiate a regression tree learner. What are the different settings for this learner? $\thetat$

<details> 
<summary>*Hint*</summary>
::: {.panel-tabset}
### R
Use `lrn("regr.rpart")` (`mlr3::mlr_learners$keys()` shows all available learners).

### Python
Use the `DecisionTreeRegressor` module and use `get_params()` to see all available settings.
:::
</details> 

::: {.content-visible when-profile="solution"}
<details> 
<summary>**Solution**</summary>
::: {.panel-tabset}
### R
{{< embed _r.ipynb#hro-learner echo=true >}}
### Python
{{< embed _python.ipynb#hro-learner echo=true >}}
:::
</details> 
:::
