<<setup-child, include=FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@


\kopf{1}
\loesung{
See R code \textbf{resampling\_l\_1.R}
}

\loesung{
<<child="../single-exercises/resampling_l_2.Rnw">>=
@
}

\loesung{
<<child="../single-exercises/mlr_l_0.Rnw">>=
@
}

\loesung{
See R code \textbf{mlr\_l\_1.R}
}

\loesung{
See R code \textbf{mlr\_l\_2.R}
}

\loesung{
<<child="../single-exercises/methods_l_1.Rnw">>=
@
}
\dlz
