% !Rnw weave = knitr

<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{9}{Random Forests}

\loesung{Classifying \texttt{spam}}{
	<<child="ex_rnw/sol_spam.Rnw">>=
	@
}

\dlz


\loesung{Decision boundaries}{

See \href{https://github.com/slds-lmu/lecture_i2ml/blob/master/exercises/forests/ex_rnw/sol_dec_boundaries.R}{R code}
}

\dlz


