<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}

\kopf{8}

\loesung{
<<child="exercises/randomForest_l_0.Rnw">>=
@
}

\dlz


\loesung{
See R code \href{https://github.com/compstat-lmu/lecture_i2ml/blob/master/exercises/forests/exercises/randomForest_l_2.R}{\textbf{randomForest\_l\_2.R}}
}

\dlz


