<<setup-child, include = FALSE>>=
knitr::set_parent("../../style/preamble_ueb.Rnw")
@

\input{../../latex-math/basic-math.tex}
\input{../../latex-math/basic-ml.tex}
\input{../../latex-math/ml-trees.tex}
\input{../../latex-math/ml-bagging.tex}

\kopf{7}

\loesung{
<<child="exercises/bagging_l_1.Rnw">>=
@
}

\dlz

\loesung{
<<child="exercises/randomForest_l_0.Rnw">>=
@
}

\dlz


\loesung{
See R code
}

\dlz
