# Source version of this workflow lives in https://github.com/slds-lmu/lecture_service/service/.github/workflows
# Please only update by copying from there to avoid divergences
# - attempts slide compilation
# - compares compiled slides against slides-pdf/
# - render HTML site and published to GitHub pages
# .. for only this particular lecture repo.
on:
  # Allow manually triggering the workflow via GitHub website, gh CLI tool etc.
  # Also adds parameter to enable tmate (inetractive tmux session for debugging)
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      cache-version:
        type: string
        description: 'Cache version identifier, increment to invalidate cache'
        required: false
        default: '1'
      tinytex-version:
        type: string
        description: 'TinyTeX version to use'
        required: false
        default: '2025.05'
  push:
    # Activate on pushes to both the main or master branches (inconsistently used across lecture repos)
    branches: [main, master]
    # Runs only when slides/, style/, or latex-math/ change
    # Also added the workflow itself to trigger a run if it changes
    # Comment out to run on every commit
    paths: ['style/**', 'slides/**', 'latex-math/**', '.github/workflows/render-lecture-slide-status.yaml']

name: render-lecture-slide-status

jobs:
  render-lecture-slide-status:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write # Required to be able to write to GitHub Pages branch
    steps:
      # Clone lecture checker repo in the current directory
      # We need lecture repo to be a sub directory of this for reasons (can optimize this once stable + working)
      - name: Checkout lecture service repo
        uses: actions/checkout@v4
        with:
          repository: slds-lmu/lecture_service
          # Don't show progress bar, very verbose for large repos
          show-progress: false

      # Most reliable way I've found to get the repo name and use it as a parameter for the checkout action
      # see https://stackoverflow.com/a/75513916/409362
      # If the repo is named slds-lmu/lecture_i2ml, we only need the "lecture_i2ml" part.
      - name: Save repository name to env var (without org)
        id: repo-basename
        run: |
          echo "value=$(basename ${{ github.repository }})" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout this lecture repo
        uses: actions/checkout@v4
        with:
          # Clone lecture repo in subdirectory of the same name
          path: ${{ steps.repo-basename.outputs.value }}
          # translates to e.g.: path: "lecture_i2ml"
          # No need for git history
          # 0 indicates all history for all branches and tags, 1 is shallow (and default)
          fetch-depth: 1
          # Don't show progress bar, very verbose for large repos
          show-progress: false

      # Caching Strategy:
      # 1. R packages: Cached based on DESCRIPTION + scripts/install_r_deps.R hash for R dependency changes
      # 2. TinyTeX: Cache entire installation (base + packages) to ensure version compatibility
      # 3. Both include cache-version input for manual cache invalidation
      # 4. Restore keys provide fallback to previous cache versions
      
      # Standard R/pandoc setup steps
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      # Get R library path for caching
      - name: Get R library dir for caching
        id: r-cache
        run: |
          echo "dir=$(Rscript --quiet -e 'cat(.libPaths()[[1]])')" >> $GITHUB_OUTPUT
      
      # Cache R packages
      - name: Cache R packages
        id: r-pkg-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.r-cache.outputs.dir }}
          key: ${{ runner.os }}-r-${{ inputs.cache-version || '1' }}-${{ hashFiles('DESCRIPTION', 'scripts/install_r_deps.R') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ inputs.cache-version || '1' }}-
            ${{ runner.os }}-r-
      
      # Check if we have a cached TinyTeX installation
      - name: Check for cached TinyTeX
        id: tinytex-cache-check
        run: |
          if [ -d "$HOME/.TinyTeX" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "📦 Found cached TinyTeX installation"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "📦 No cached TinyTeX found, will install fresh"
          fi
      
      # Setup TinyTeX only if not cached
      # Use a fixed version instead of daily build for stability
      - uses: r-lib/actions/setup-tinytex@v2
        if: steps.tinytex-cache-check.outputs.exists == 'false'
        env:
          TINYTEX_VERSION: ${{ inputs.tinytex-version || '2025.05' }}
      
      # Cache the entire TinyTeX installation (base + packages)
      - name: Cache TinyTeX installation
        id: tinytex-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.TinyTeX
            ~/bin
          key: ${{ runner.os }}-tinytex-${{ inputs.tinytex-version || '2025.05' }}-${{ inputs.cache-version || '1' }}-${{ hashFiles('scripts/install_tex_deps.R') }}
          restore-keys: |
            ${{ runner.os }}-tinytex-${{ inputs.tinytex-version || '2025.05' }}-${{ inputs.cache-version || '1' }}-
      
      # Ensure TinyTeX is in PATH if restored from cache
      - name: Setup TinyTeX PATH
        if: steps.tinytex-cache.outputs.cache-hit == 'true'
        run: |
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "$HOME/.TinyTeX/bin/x86_64-linux" >> $GITHUB_PATH
      
      - run: tlmgr --version

      # Setting up the lecture checking requirements:
      # 1) R packages
      - name: Install R packages
        run: make install-r
      
      # 2) LaTeX packages - install only if cache miss
      - name: Install additional LaTeX packages
        if: steps.tinytex-cache.outputs.cache-hit != 'true'
        run: |
          echo "📦 Installing LaTeX packages (no cache found)..."
          make install-tex
          
          # Show summary of installed packages
          installed_count=$(tlmgr list --only-installed | grep -E '^i ' | wc -l)
          echo "📦 Total LaTeX packages installed: $installed_count"
      
      # Verify installation when using cache
      - name: Verify LaTeX installation
        if: steps.tinytex-cache.outputs.cache-hit == 'true'
        run: |
          echo "✅ Using cached TinyTeX installation"
          # Quick verification of critical packages
          for pkg in beamer pgf xcolor tikzmark tcolorbox; do
            if tlmgr list --only-installed "$pkg" >/dev/null 2>&1; then
              echo "✓ Package $pkg is installed"
            else
              echo "❌ Package $pkg is missing - cache may be incomplete"
            fi
          done
          installed_count=$(tlmgr list --only-installed | grep -E '^i ' | wc -l)
          echo "📦 Total LaTeX packages in cache: $installed_count"
      
      # Cache effectiveness summary
      - name: Cache effectiveness summary
        run: |
          echo "## 📊 Cache Status Summary"
          echo "- R packages cache: ${{ steps.r-pkg-cache.outputs.cache-hit == 'true' && '✅ HIT' || '❌ MISS' }}"
          echo "- TinyTeX cache: ${{ steps.tinytex-cache.outputs.cache-hit == 'true' && '✅ HIT' || '❌ MISS' }}"
          echo "- Cache version: ${{ inputs.cache-version || '1' }}"
          if [ "${{ steps.tinytex-cache.outputs.cache-hit }}" = "true" ]; then
            echo "- ⚡ TinyTeX cache saved ~3-4 minutes of installation time"
          fi
      # 3) Installing diff-pdf and diff-pdf-visually (only automated for ubuntu so far)
      # - name: Install diff-pdf and diff-pdf-visually
      #   run: make install-tools-ubuntu

      - name: Install the service package
        run: make install-service

      # Get a tmux ssh session for interactive debugging
      # Controlled via inputs from GitHub webinterface
      # See https://github.com/mxschmitt/action-tmate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      # Run the main thing: compiles slides, checks against slides-pdf/*, renders Rmd -> html site with results
      # Resulting output is in ./_site
      # Before we add the lecture dir (e.g. "lecture_sl") to the include_lectures file to
      # ensure that we do not accidentally skip this lecture, as this file is usually used
      # to specify lecture for which `make site` should do something
      - name: Check slides and build HTML overview
        run: |
          echo $(basename $PWD) > include_lectures
          make site

      # Deploy using this rather than JamesIves/github-pages-deploy-action, as this supports pushing
      # orphan branches. Since we're adding a bunch of PDFs, we really want to avoid a bloated branch history
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
          

      # Helper script generates exit status 1 if at least one slide failed to compile
      - name: Generate exit code based on check status
        run: |
          ./inst/check_status.R
